#include "MeshBooleanInputTopologyFixtures.h"
#include <iostream>
using namespace input_test;
template<class T,class I>void valid(){auto a=tetra<T,I>(),b=fv_surface_mesh<T,I>{};auto r=registry();auto c=context(a,b,r);auto x=validate_operands(*c);require(x.has_value(),"tetra validates");require(x.value()->payload->vertices.size()==4,"vertices");require(x.value()->payload->facets.size()==4,"facets");require(x.value()->payload->edges.size()==6,"edges");require(x.value()->payload->shells.size()==1,"shell");require(x.value()->payload->operands[0].bounds.has_value(),"operand bounds");require(x.value()->payload->evidence.size()==14,"artifact evidence summaries");require(x.value()->report.passed()&&!x.value()->report.evidence.empty(),"verified evidence");}
template<class T,class I>void malformed(){auto a=tetra<T,I>(),b=fv_surface_mesh<T,I>{};a.faces[0][0]=I(99);auto r=registry();auto c=context(a,b,r);auto x=validate_operands(*c);require(!x.has_value(),"bad index rejected");require(x.error().code==boolean_error_code::input_contract_error,"input error");}
template<class T,class I>void polygon(){auto a=cube<T,I>(),b=fv_surface_mesh<T,I>{};auto r=registry();auto c=context(a,b,r);auto x=validate_operands(*c);require(x.has_value(),"quad cube validates");require(x.value()->payload->facets.size()==6,"polygon facets");for(const auto&f:x.value()->payload->facets)require(f.triangles.size()==2,"exact quad triangulation");}
template<class T,class I>void cavity(){auto a=box<T,I>(T(0),T(4));append(a,box<T,I>(T(1),T(2)),true);fv_surface_mesh<T,I>b;auto r=registry();auto c=context(a,b,r);auto x=validate_operands(*c);if(!x.has_value())throw std::runtime_error("nested cavity: "+render_error(x.error()));require(x.value()->payload->shells.size()==2,"two nested shells");std::size_t cavities=0;for(const auto&s:x.value()->payload->shells)if(s.contribution==shell_contribution::cavity_boundary){++cavities;require(s.depth==1&&s.orientation==shell_orientation::inward,"cavity semantics");}require(cavities==1,"one cavity");auto bad=box<T,I>(T(0),T(4));append(bad,box<T,I>(T(1),T(2)));auto c2=context(bad,b,r);auto y=validate_operands(*c2);require(!y.has_value()&&y.error().subcode==static_cast<std::uint32_t>(input_validation_subcode::orientation_mismatch),"bad cavity orientation rejected");}
template<class T,class I>void shell_contacts(){for(T shift:{T(1),T(2)}){auto a=box<T,I>(T(0),T(2));append(a,box<T,I>(shift,shift+T(2)));fv_surface_mesh<T,I>b;auto r=registry();auto c=context(a,b,r);auto x=validate_operands(*c);require(!x.has_value(),shift==T(1)?"crossing shells rejected":"touching shells rejected");require(x.error().subcode==static_cast<std::uint32_t>(input_validation_subcode::shell_contact),"shell contact code");}}
template<class T,class I>void difficult_polygons(){for(bool collinear:{false,true}){auto a=prism<T,I>(collinear);fv_surface_mesh<T,I>b;auto r=registry();auto c=context(a,b,r);auto x=validate_operands(*c);require(x.has_value(),collinear?"collinear polygon validates":"concave polygon validates");}}
int main(){try{valid<float,std::uint32_t>();valid<float,std::uint64_t>();valid<double,std::uint32_t>();valid<double,std::uint64_t>();polygon<float,std::uint32_t>();polygon<double,std::uint64_t>();cavity<double,std::uint32_t>();shell_contacts<double,std::uint32_t>();difficult_polygons<double,std::uint32_t>();malformed<float,std::uint32_t>();malformed<double,std::uint64_t>();std::cout<<"PASS input topology\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL "<<e.what()<<'\n';return 1;}}
