#include "MeshBooleanInputTopologyFixtures.h"
#include <algorithm>
#include <iostream>
using namespace input_test;
namespace {
template<class T>std::size_t exhaustive_rotation(const std::vector<T>&v){std::size_t best=0;for(std::size_t candidate=1;candidate<v.size();++candidate){std::vector<T>a,b;for(std::size_t i=0;i<v.size();++i){a.push_back(v[(candidate+i)%v.size()]);b.push_back(v[(best+i)%v.size()]);}if(a<b)best=candidate;}return best;}
template<class T>std::vector<T>rotation_key(const std::vector<T>&v,std::size_t shift){std::vector<T>out;for(std::size_t i=0;i<v.size();++i)out.push_back(v[(shift+i)%v.size()]);return out;}
void rotation_oracle(){std::uint32_t state=0x9e3779b9U;for(std::size_t n=1;n<=12;++n)for(std::size_t sample=0;sample<256;++sample){std::vector<std::uint32_t>values(n);for(auto&v:values){state=state*1664525U+1013904223U;v=(state>>28)+(sample%3);}const auto linear=input_topology_detail::minimal_cyclic_rotation(values),exhaustive=exhaustive_rotation(values);require(rotation_key(values,linear)==rotation_key(values,exhaustive),"linear rotation matches exhaustive oracle");auto reversed=values;std::reverse(reversed.begin(),reversed.end());const auto forward_key=rotation_key(values,linear),reverse_key=rotation_key(reversed,input_topology_detail::minimal_cyclic_rotation(reversed));const auto exhaustive_unoriented=std::min(rotation_key(values,exhaustive),rotation_key(reversed,exhaustive_rotation(reversed)));require(std::min(forward_key,reverse_key)==exhaustive_unoriented,"unoriented rotation matches exhaustive oracle");}}
bool same_plane(const exact_plane3&a,const exact_plane3&b){return a.a==b.a&&a.b==b.b&&a.c==b.c&&a.d==b.d&&a.oriented==b.oriented;}
template<class T,class I>void artifact_oracles(){auto a=prism<T,I>(true),b=fv_surface_mesh<T,I>{};auto r=registry();auto c=context(a,b,r);auto x=validate_operands(*c);require(x.has_value(),"oracle prism validates");const auto&artifact=*x.value()->payload;for(std::size_t raw_face=0;raw_face<a.faces.size();++raw_face){const auto&facet=artifact.facets[artifact.raw_facets[0][raw_face].value_for_debug()];std::vector<original_vertex_id>raw_ids;for(auto raw_vertex:a.faces[raw_face]){const auto provenance=artifact.raw_vertex_provenance[0][raw_vertex];raw_ids.push_back(*artifact.provenance[provenance].canonical_vertex);}const auto expected=rotation_key(raw_ids,exhaustive_rotation(raw_ids));require(facet.ring==expected,"stored ring matches exhaustive rotation");status_or<exact_plane3>plane=make_error(boolean_error_code::input_contract_error,boolean_stage::input_validation,"no_support");for(std::size_t i=0;i<facet.ring.size()&&!plane.has_value();++i)for(std::size_t j=i+1;j<facet.ring.size()&&!plane.has_value();++j)for(std::size_t k=j+1;k<facet.ring.size()&&!plane.has_value();++k)plane=support_plane_dyadic(artifact.vertices[facet.ring[i].value_for_debug()].exact_coordinate,artifact.vertices[facet.ring[j].value_for_debug()].exact_coordinate,artifact.vertices[facet.ring[k].value_for_debug()].exact_coordinate);require(plane.has_value()&&same_plane(plane.value(),facet.plane),"linear support plane matches exhaustive triple oracle");}}
}
template<class T,class I>void rotated(){auto a=tetra<T,I>(),b=fv_surface_mesh<T,I>{};for(auto&f:a.faces)std::rotate(f.begin(),f.begin()+1,f.end());std::reverse(a.faces.begin(),a.faces.end());auto r=registry();auto c=context(a,b,r);auto x=validate_operands(*c);require(x.has_value(),"rotated rings and facets validate");require(x.value()->payload->edges.size()==6,"edge reconstruction");}
template<class T,class I>void canonical_digest(){auto a=prism<T,I>(true),permuted=a,b=fv_surface_mesh<T,I>{};std::reverse(permuted.vertices.begin(),permuted.vertices.end());for(auto&f:permuted.faces)for(auto&v:f)v=static_cast<I>(permuted.vertices.size()-1-v);for(auto&f:permuted.faces)std::rotate(f.begin(),f.begin()+2%f.size(),f.end());std::reverse(permuted.faces.begin(),permuted.faces.end());auto r=registry();auto c1=context(a,b,r),c2=context(permuted,b,r);auto x=validate_operands(*c1),y=validate_operands(*c2);require(x.has_value()&&y.has_value(),"permutations validate");require(x.value()->payload->operands[0].semantic_digest==y.value()->payload->operands[0].semantic_digest,"canonical semantic digest");require(x.value()->payload->artifact_digest!=y.value()->payload->artifact_digest,"provenance-bound artifact digest");}
template<class T,class I>void repeated_determinism(){auto a=prism<T,I>(true),b=fv_surface_mesh<T,I>{};auto r=registry();std::optional<digest>artifact,report;for(int i=0;i<8;++i){auto c=context(a,b,r);auto x=validate_operands(*c);require(x.has_value(),"repeated validation");if(artifact){require(*artifact==x.value()->payload->artifact_digest,"repeated artifact digest");require(*report==x.value()->report.report_digest,"repeated report digest");}else{artifact=x.value()->payload->artifact_digest;report=x.value()->report.report_digest;}}}
template<class T,class I>void component_permutation(){auto a=box<T,I>(T(0),T(1)),permuted=box<T,I>(T(3),T(4)),b=fv_surface_mesh<T,I>{};append(a,box<T,I>(T(3),T(4)));append(permuted,box<T,I>(T(0),T(1)));auto r=registry();auto c1=context(a,b,r),c2=context(permuted,b,r);auto x=validate_operands(*c1),y=validate_operands(*c2);require(x.has_value()&&y.has_value(),"component permutations validate");require(x.value()->payload->operands[0].semantic_digest==y.value()->payload->operands[0].semantic_digest,"component permutation semantic digest");}
int main(){try{rotation_oracle();rotated<float,std::uint32_t>();rotated<float,std::uint64_t>();rotated<double,std::uint32_t>();rotated<double,std::uint64_t>();canonical_digest<double,std::uint32_t>();artifact_oracles<double,std::uint32_t>();component_permutation<double,std::uint32_t>();repeated_determinism<double,std::uint32_t>();std::cout<<"PASS input properties\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL "<<e.what()<<'\n';return 1;}}
