#include "MeshBooleanCellClassificationFixtures.h"
#include <iostream>
using namespace classification_test;
template<class T,class I>
static fv_surface_mesh<T,I> subdivided_square_prism(std::size_t subdivisions){
  fv_surface_mesh<T,I> mesh;std::vector<std::array<T,2>> ring;
  for(std::size_t i=0;i<subdivisions;++i)ring.push_back({T(i),T(0)});
  for(std::size_t i=0;i<subdivisions;++i)ring.push_back({T(subdivisions),T(i)});
  for(std::size_t i=0;i<subdivisions;++i)ring.push_back({T(subdivisions-i),T(subdivisions)});
  for(std::size_t i=0;i<subdivisions;++i)ring.push_back({T(0),T(subdivisions-i)});
  for(T z:{T(0),T(1)})for(const auto&p:ring)mesh.vertices.push_back({p[0],p[1],z});
  std::vector<I> bottom,top;for(std::size_t i=0;i<ring.size();++i){bottom.push_back(static_cast<I>(ring.size()-1-i));top.push_back(static_cast<I>(ring.size()+i));}mesh.faces.push_back(std::move(bottom));mesh.faces.push_back(std::move(top));
  for(std::size_t i=0;i<ring.size();++i){const auto next=(i+1)%ring.size();mesh.faces.push_back({static_cast<I>(i),static_cast<I>(next),static_cast<I>(ring.size()+next),static_cast<I>(ring.size()+i)});}return mesh;
}
struct verifier_facet_node_layout{exact_box3 bounds;std::size_t begin=0,end=0,left=0,right=0;bool leaf=true;};
struct verifier_edge_key_layout{operand_id operand;original_vertex_id first,second;};
struct verifier_directed_edge_key_layout{original_vertex_id first,second;};
template<class T,class I>
static std::array<std::uint64_t,3> classification_geometry_storage(const validated_operands<T,I>&v){
  std::uint64_t facets=0,triangles=0,ring_entries=0,fan_members=0,duplicated_payload=0;
  for(const auto&f:v.facets){++facets;triangles+=f.triangles.size();ring_entries+=f.ring.size();const auto&g=v.facet_geometry[f.id.value_for_debug()];std::uint64_t members=0;for(const auto&fan:g.vertex_fans)members+=fan.size();fan_members+=members;const auto per_ring=f.ring.size()*(sizeof(exact_point3)+sizeof(exact_point2)+sizeof(original_vertex_id)+sizeof(std::vector<facet_id>))+members*sizeof(facet_id);duplicated_payload+=per_ring*f.triangles.size();}
  std::function<std::uint64_t(std::uint64_t)>nodes=[&](std::uint64_t count){return count==0?std::uint64_t(0):count<=8?std::uint64_t(1):std::uint64_t(1)+nodes(count/2)+nodes(count-count/2);};const auto common=facets*sizeof(sourced_exact_facet3)+triangles*sizeof(sourced_exact_triangle3)+ring_entries*(sizeof(exact_point3)+sizeof(exact_point2)+sizeof(original_vertex_id)+sizeof(std::vector<facet_id>))+fan_members*sizeof(facet_id)+facets*(sizeof(exact_box3)+sizeof(std::size_t));const auto producer=common+triangles*(sizeof(exact_box3)+sizeof(std::size_t))+nodes(triangles)*sizeof(sourced_exact_ray_index_node3);const auto attribution=facets*sizeof(std::vector<verifier_directed_edge_key_layout>)+ring_entries*sizeof(verifier_directed_edge_key_layout)+v.edges.size()*sizeof(std::pair<verifier_edge_key_layout,std::size_t>);const auto verifier=common+nodes(facets)*sizeof(verifier_facet_node_layout)+attribution;return {producer,verifier,duplicated_payload};
}
static void facet_storage_accounting(){
  auto measure=[](std::size_t subdivisions){auto a=subdivided_square_prism<double,std::uint32_t>(subdivisions);fv_surface_mesh<double,std::uint32_t>b;boolean_options options;options.tracing.collect_noncanonical_timings=true;auto c=classification_test::context(a,b,classification_test::registry(),operation::regularized_union,options);auto result=classify_arrangement_cells(*c);require(result.has_value(),"highly triangulated classification");classification_oracle(*result.value()->payload);const auto expected=classification_geometry_storage(*result.value()->payload->validated->payload);const auto&stage=c->performance()->stage(boolean_stage::cell_classification);require(stage.producer.resource(resource_kind::stage_private_bytes)==expected[0],"producer facet classification storage accounting");require(stage.verifier.resource(resource_kind::verifier_scratch_bytes)==expected[1],"verifier facet classification storage accounting");require(stage.producer.value(performance_counter::exact_ray_facet_tests)<=stage.producer.value(performance_counter::ray_box_candidates),"producer exact tests limited to ray-bound candidates");require(stage.producer.value(performance_counter::exact_ray_facet_tests)<stage.producer.value(performance_counter::classification_source_triangles),"producer ray index reduces exhaustive triangle tests");const auto expected_rays=result.value()->payload->seeds.size()*4+2;require(stage.verifier.value(performance_counter::reconstructed_rays)==expected_rays,"verifier reconstructs each unique evidence ray once");require(stage.verifier.value(performance_counter::exact_ray_facet_tests)==stage.verifier.value(performance_counter::ray_box_candidates),"verifier exact tests equal indexed facet candidates");require(stage.verifier.value(performance_counter::accepted_ray_hits)<=stage.verifier.value(performance_counter::exact_ray_facet_tests),"verifier accepted hits bounded by exact tests");return expected;};
  const auto small=measure(4),large=measure(8);require(large[0]<small[0]*3,"classification storage scales linearly with polygon triangulation");require(large[2]>large[0],"ring and fan storage charged per facet rather than triangle");
  auto a=subdivided_square_prism<double,std::uint32_t>(4);fv_surface_mesh<double,std::uint32_t>b;boolean_options short_limit;short_limit.resources.stage_private_bytes={false,small[0]-1};auto c=classification_test::context(a,b,classification_test::registry(),operation::regularized_union,short_limit);auto arrangement=build_global_arrangement(*c);require(arrangement.has_value(),"classification byte-limit prerequisite");const auto before=c->accountant().used(resource_kind::stage_private_bytes);auto rejected=classify_arrangement_cells(*c);require(!rejected.has_value()&&rejected.error().code==boolean_error_code::resource_limit&&rejected.error().stage==boolean_stage::cell_classification,"classification geometry one-under byte limit");require(c->artifacts().latest_generation(artifact_slot::labeled_arrangement)==0&&c->accountant().used(resource_kind::stage_private_bytes)==before,"classification geometry byte rollback");
  auto verifier_registry=classification_test::registry();auto verifier_context=classification_test::context(a,b,verifier_registry,operation::regularized_union);auto verified_artifact=classify_arrangement_cells(*verifier_context);require(verified_artifact.has_value(),"classification verifier limit fixture");const auto type=labeled_arrangement_type_tag+(static_cast<std::uint64_t>(coordinate_tag::binary64)<<8)+static_cast<std::uint64_t>(index_tag::uint32);auto spec=verifier_registry->specification(artifact_slot::labeled_arrangement,type,labeled_arrangement_schema,verification_level::mandatory);require(spec.has_value(),"classification verifier limit specification");artifact_view view{verifier_context->owner(),artifact_slot::labeled_arrangement,type,labeled_arrangement_schema,1,verified_artifact.value()->artifact_digest,verified_artifact.value()->payload,verified_artifact.value()->payload.get()};auto verify_limit=[&](resource_kind kind,std::uint64_t limit){resource_policy policy;if(kind==resource_kind::verifier_work)policy.verifier_work={false,limit};else policy.verifier_scratch_bytes={false,limit};resource_accountant accountant(policy);verification_environment_view env{verifier_context->owner(),verifier_context->replay().setup,verifier_context->contract().selected_operation(),&verifier_context->options(),coordinate_tag::binary64,index_tag::uint32,&verifier_context->kernel(),{},&accountant,[]{return false;}};auto checked=verifier_registry->verify(view,spec.value(),env);require(accountant.used(resource_kind::verifier_work)==0&&accountant.used(resource_kind::verifier_scratch_bytes)==0,"classification verifier resource rollback");return checked;};const auto&verified=*verified_artifact.value()->payload;const auto verifier_work=(verified.seeds.size()*4+2)*verified.validated->payload->facets.size()+verified.transitions.size()+verified.canonical_bytes.size();for(const auto&entry:std::array<std::pair<resource_kind,std::uint64_t>,2>{{{resource_kind::verifier_scratch_bytes,small[1]},{resource_kind::verifier_work,verifier_work}}}){require(entry.second>0,"classification verifier resource measured");auto exact_verification=verify_limit(entry.first,entry.second);require(exact_verification.has_value()&&exact_verification.value().passed(),"classification verifier exact resource limit");auto short_verification=verify_limit(entry.first,entry.second-1);require(!short_verification.has_value()&&short_verification.error().code==boolean_error_code::resource_limit&&short_verification.error().stage==boolean_stage::cell_classification,"classification verifier one-under resource limit");}
}
static void bounded_verifier_index_differential(){
  struct policy_scope{formal_ray_index_execution_policy previous=formal_ray_index_policy::test_execution_policy();~policy_scope(){formal_ray_index_policy::exchange_test_execution_policy(previous);}} scope;
  std::uint32_t state=0x91e10da5U;bool pruned=false;
  for(std::size_t case_index=0;case_index<6;++case_index){state=state*1664525U+1013904223U;const double x=double(int((state>>8)%17)-8)/4.0;state=state*1664525U+1013904223U;const double y=double(int((state>>8)%17)-8)/4.0;auto a=input_test::box<double,std::uint32_t>(0.0,2.0),b=input_test::box<double,std::uint32_t>(0.0,1.0);translate(b,x,y,double(case_index%3)-1.0);boolean_options options;options.tracing.collect_noncanonical_timings=true;formal_ray_index_policy::exchange_test_execution_policy(formal_ray_index_execution_policy::accelerated);auto indexed_context=context(a,b,classification_test::registry(),operation::regularized_union,options);auto indexed=classify_arrangement_cells(*indexed_context);require(indexed.has_value(),"bounded indexed verifier case");formal_ray_index_policy::exchange_test_execution_policy(formal_ray_index_execution_policy::exhaustive);auto exhaustive_context=context(a,b,classification_test::registry(),operation::regularized_union,options);auto exhaustive=classify_arrangement_cells(*exhaustive_context);require(exhaustive.has_value(),"bounded exhaustive verifier case");require(indexed.value()->payload->canonical_bytes==exhaustive.value()->payload->canonical_bytes,"bounded exhaustive/indexed verifier evidence");const auto indexed_tests=indexed_context->performance()->stage(boolean_stage::cell_classification).verifier.value(performance_counter::exact_ray_facet_tests);const auto exhaustive_tests=exhaustive_context->performance()->stage(boolean_stage::cell_classification).verifier.value(performance_counter::exact_ray_facet_tests);require(indexed_tests<=exhaustive_tests,"indexed verifier work bounded by exhaustive scan");pruned=pruned||indexed_tests<exhaustive_tests;}
  require(pruned,"bounded verifier hierarchy prunes facet tests");
}
template<class T,class I>
static void qualification(){
  auto a=input_test::box<T,I>(T(0),T(1)),b=input_test::box<T,I>(T(3),T(4));
  boolean_options one;one.execution.max_threads=1;auto c1=context(a,b,classification_test::registry(),operation::regularized_union,one);auto x=classify_arrangement_cells(*c1);require(x.has_value(),"classification single-thread schedule");
  boolean_options many;many.execution.max_threads=4;auto c4=context(a,b,classification_test::registry(),operation::regularized_union,many);auto y=classify_arrangement_cells(*c4);require(y.has_value(),"classification multi-thread schedule");require(x.value()->payload->canonical_bytes==y.value()->payload->canonical_bytes,"classification schedule determinism");

  auto translated_a=a,translated_b=b;translate(translated_a,T(8),T(-4),T(2));translate(translated_b,T(8),T(-4),T(2));auto translated_context=context(translated_a,translated_b,classification_test::registry());auto translated=classify_arrangement_cells(*translated_context);require(translated.has_value(),"translated classification");require(label_histogram(*translated.value()->payload)==label_histogram(*x.value()->payload),"translation-equivariant labels");
  auto scaled_a=input_test::box<T,I>(T(0),T(2)),scaled_b=input_test::box<T,I>(T(6),T(8));auto scaled_context=context(scaled_a,scaled_b,classification_test::registry());auto scaled=classify_arrangement_cells(*scaled_context);require(scaled.has_value(),"scaled classification");require(label_histogram(*scaled.value()->payload)==label_histogram(*x.value()->payload),"power-of-two scale-equivariant labels");
  auto swapped_context=context(b,a,classification_test::registry());auto swapped=classify_arrangement_cells(*swapped_context);require(swapped.has_value(),"operand-swapped classification");auto expected=label_histogram(*x.value()->payload);std::swap(expected[1],expected[2]);require(label_histogram(*swapped.value()->payload)==expected,"operand-swap occupancy mapping");

  cancellation_source stop;auto cancelled_context=context(a,b,classification_test::registry(),operation::regularized_union,boolean_options{},&stop);stop.cancel();auto cancelled=classify_arrangement_cells(*cancelled_context);require(!cancelled.has_value()&&cancelled.error().code==boolean_error_code::resource_limit,"classification cancellation category");require(cancelled_context->artifacts().latest_generation(artifact_slot::labeled_arrangement)==0,"classification cancellation rollback");

  const auto&base=*x.value()->payload;
  using member=resource_limit resource_policy::*;
  const std::array<std::tuple<member,resource_kind,std::uint64_t>,5> limits{{
    {&resource_policy::cells,resource_kind::cells,base.regions.size()},
    {&resource_policy::seed_certificates,resource_kind::seed_certificates,base.seeds.size()},
    {&resource_policy::classification_transitions,resource_kind::classification_transitions,base.transitions.size()},
    {&resource_policy::patch_side_labels,resource_kind::patch_side_labels,base.side_labels.size()},
    {&resource_policy::propagation_records,resource_kind::propagation_records,base.propagation.size()}}};
  for(const auto&entry:limits){const auto field=std::get<0>(entry);const auto kind=std::get<1>(entry);const auto required=std::get<2>(entry);require(required>0,"classification resource fixture");boolean_options exact;exact.resources.*field={false,required};auto exact_context=context(a,b,classification_test::registry(),operation::regularized_union,exact);auto accepted=classify_arrangement_cells(*exact_context);require(accepted.has_value(),"classification exact resource limit");require(exact_context->accountant().used(kind)==required,"classification exact resource charge");boolean_options short_limit;short_limit.resources.*field={false,required-1};auto short_context=context(a,b,classification_test::registry(),operation::regularized_union,short_limit);auto rejected=classify_arrangement_cells(*short_context);require(!rejected.has_value()&&rejected.error().code==boolean_error_code::resource_limit,"classification one-under resource rejection");require(short_context->artifacts().latest_generation(artifact_slot::labeled_arrangement)==0&&short_context->accountant().used(kind)==0,"classification resource rollback");}

  auto equal_a=input_test::box<T,I>(T(0),T(1)),equal_b=equal_a;auto equal_context=context(equal_a,equal_b,classification_test::registry());auto equal=classify_arrangement_cells(*equal_context);require(equal.has_value(),"equal classification");std::uint64_t coincident=0;for(const auto&t:equal.value()->payload->transitions)if(t.crossing==classification_crossing_kind::coincident){++coincident;require(t.transfer==classification_transfer_kind::both&&t.coincidence&&t.uses.size()==2,"complete coincident transfer provenance");}require(coincident>0,"equal solids have coincident transfers");
  auto partial_b=equal_b;translate(partial_b,T(0.5),T(0),T(0));auto partial_context=context(equal_a,partial_b,classification_test::registry());auto partial=classify_arrangement_cells(*partial_context);require(partial.has_value(),"partial coincidence classification");require(!partial.value()->payload->arrangement->payload->coincident_groups.empty(),"partial coincidence retained");
}
int main(){try{
  const auto operations={operation::regularized_union,operation::regularized_intersection,operation::a_minus_b,operation::b_minus_a,operation::symmetric_difference};
  auto run=[](auto scalar,auto index){using T=decltype(scalar);using I=decltype(index);
    run_analytic_classification_case<T,I>(classification_test::registry(),T(0),T(1),T(3),T(4));
    run_analytic_classification_case<T,I>(classification_test::registry(),T(0),T(3),T(1),T(2));
    run_analytic_classification_case<T,I>(classification_test::registry(),T(0),T(1),T(0),T(1));
    run_analytic_classification_case<T,I>(classification_test::registry(),T(0),T(2),T(1),T(3));
    run_analytic_classification_case<T,I>(classification_test::registry(),T(0),T(1),T(1),T(2));
  };
  run(float{},std::uint32_t{});run(float{},std::uint64_t{});run(double{},std::uint32_t{});run(double{},std::uint64_t{});

  std::vector<std::uint8_t> operation_independent;
  for(auto op:operations){auto bytes=run_analytic_classification_case<double,std::uint32_t>(classification_test::registry(),0.0,2.0,1.0,3.0,op);if(operation_independent.empty())operation_independent=std::move(bytes);else require(bytes==operation_independent,"classification canonical bytes independent of operation");}

  auto r=classification_test::registry();auto cavity=input_test::box<double,std::uint32_t>(0.0,6.0);input_test::append(cavity,input_test::box<double,std::uint32_t>(1.0,5.0),true);input_test::append(cavity,input_test::box<double,std::uint32_t>(2.0,4.0),false);fv_surface_mesh<double,std::uint32_t> empty;auto cavity_context=context(cavity,empty,r);auto cavity_result=classify_arrangement_cells(*cavity_context);if(!cavity_result.has_value())throw std::runtime_error("nested classification: "+render_error(cavity_result.error()));classification_oracle(*cavity_result.value()->payload);require(cavity_result.value()->payload->validated->payload->shells.size()==3,"classification retains nested shells");unsigned material=0,cavity_boundary=0;for(const auto&s:cavity_result.value()->payload->validated->payload->shells){material+=s.contribution==shell_contribution::material_boundary;cavity_boundary+=s.contribution==shell_contribution::cavity_boundary;}require(material==2&&cavity_boundary==1,"classification alternating shell polarity evidence");

  auto empty_context=context(empty,empty,classification_test::registry());auto empty_result=classify_arrangement_cells(*empty_context);if(!empty_result.has_value())throw std::runtime_error("empty classification: "+render_error(empty_result.error()));classification_oracle(*empty_result.value()->payload);require(empty_result.value()->payload->regions.size()==1,"empty universe region");require(empty_result.value()->payload->patch_labels.empty(),"empty universe has no patch labels");
  qualification<double,std::uint32_t>();
  facet_storage_accounting();
  bounded_verifier_index_differential();
  std::cout<<"ok\n";}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
