#include <YgorMeshesBooleanContract.h>
#include <YgorMeshesBooleanExecutor.h>
#include <YgorMeshesBooleanTransaction.h>
#include <algorithm>
#include <iostream>
#include <memory>
#include <stdexcept>
#include <type_traits>
using namespace ygor::mesh_boolean;
static void require(bool v,const char*m){if(!v)throw std::runtime_error(m);}
static void truth(){for(unsigned op=0;op<5;++op){operation_contract c(static_cast<operation>(op));for(unsigned a=0;a<2;++a)for(unsigned b=0;b<2;++b)require(c.occupied(a,b)==operation_value(static_cast<operation>(op),a,b),"truth table");}operation_contract d(operation::a_minus_b);require(d.occupied(true,false)&&!d.occupied(false,true),"ordered difference");require(d.patch_orientation({true,false},{false,false})==1,"orientation");require(d.patch_orientation({false,false},{false,false})==0,"rejected patch");}
static void ids(){static_assert(!std::is_convertible<facet_id,raw_event_id>::value,"IDs differ");static_assert(!std::is_convertible<std::uint64_t,facet_id>::value,"integer conversion");require(!facet_id{}.valid(),"sentinel");canonical_encoder e;e.id(facet_id::from_canonical_value(0x0102));const auto&b=e.bytes();require(b.size()==8&&b[6]==1&&b[7]==2,"big endian ID");}
static void encoding(){canonical_encoder e;e.boolean(true);e.u16(0x1234);e.u32(0x01020304);require((e.bytes()==std::vector<std::uint8_t>{1,0x12,0x34,1,2,3,4}),"canonical bytes");require(md5_digest(nullptr,0).hex()=="d41d8cd98f00b204e9800998ecf8427e","MD5 vector");}
static void options(){boolean_options o;require(validate_options(o).has_value(),"default options");o.execution.max_threads=0;require(!validate_options(o).has_value(),"invalid threads");static_assert(is_supported_boolean_types<float,std::uint32_t>::value,"supported");static_assert(!is_supported_boolean_types<long double,std::uint32_t>::value,"unsupported coordinate");}
static void arithmetic(){require(checked_add(2,3).value()==5,"add");require(!checked_add(UINT64_MAX,1).has_value(),"add overflow");require(!checked_multiply(UINT64_MAX,2).has_value(),"multiply overflow");resource_policy p;p.work_units={false,2};resource_accountant a(p);require(a.reserve(resource_kind::work_units,2,boolean_stage::broad_phase).has_value(),"reserve");require(!a.reserve(resource_kind::work_units,1,boolean_stage::broad_phase).has_value(),"limit");a.release(resource_kind::work_units,2);require(a.used(resource_kind::work_units)==0,"release");cancellation_source s;auto t=s.token();require(!t.cancelled(),"not cancelled");s.cancel();require(t.cancelled(),"cancelled");}
static void canonical_ids(){using F=canonical_id_factory<facet_id,int,int>;std::vector<F::provisional>v{{3,30},{1,10},{3,30},{2,20}};auto r=F::assign(std::move(v),[](int a,int b)noexcept{return a<b;},[](auto b,auto e)->status_or<int>{int x=b->record;for(;b!=e;++b)if(b->record!=x)return make_error(boolean_error_code::internal_invariant_error,boolean_stage::input_validation,"conflict");return x;});require(r.has_value()&&r.value().size()==3,"canonical groups");require(r.value()[0].second==10&&r.value()[2].first.value_for_debug()==2,"canonical order");}
static void generations(){auto owner=make_context_owner_token();artifact_generation_catalog catalog(owner);auto first=std::make_shared<const int>(1),second=std::make_shared<const int>(2);auto g1=catalog.compare_and_publish(artifact_slot::symbolic_complex,0,owner,first);require(g1.has_value()&&g1.value()==1,"first generation");auto stale=catalog.compare_and_publish(artifact_slot::symbolic_complex,0,owner,second);require(!stale.has_value()&&catalog.latest_generation(artifact_slot::symbolic_complex)==1,"stale writer rejected");auto retained=catalog.latest(artifact_slot::symbolic_complex);auto g2=catalog.compare_and_publish(artifact_slot::symbolic_complex,1,owner,second);require(g2.has_value()&&g2.value()==2,"successor generation");require(*std::static_pointer_cast<const int>(retained)==1&&*std::static_pointer_cast<const int>(catalog.latest(artifact_slot::symbolic_complex))==2,"prior generation retained");artifact_generation_catalog foreign(make_context_owner_token());require(!foreign.compare_and_publish(artifact_slot::symbolic_complex,0,owner,first).has_value(),"owner mismatch rejected");}
int main(){struct test{const char*n;void(*f)();};test ts[]={{"truth",truth},{"ids",ids},{"encoding",encoding},{"options",options},{"arithmetic",arithmetic},{"canonical_ids",canonical_ids},{"generations",generations}};int failures=0;for(auto&t:ts)try{t.f();std::cout<<"PASS "<<t.n<<'\n';}catch(const std::exception&e){++failures;std::cerr<<"FAIL "<<t.n<<": "<<e.what()<<'\n';}return failures?1:0;}
