#include "MeshBooleanInputTopologyFixtures.h"
#include <YgorMeshesBooleanPerformance.h>
#include <algorithm>
#include <iostream>
using namespace input_test;
template<class T,class I>void valid(){auto a=tetra<T,I>(),b=fv_surface_mesh<T,I>{};auto r=registry();auto c=context(a,b,r);auto x=validate_operands(*c);require(x.has_value(),"tetra validates");require(x.value()->payload->vertices.size()==4,"vertices");require(x.value()->payload->facets.size()==4,"facets");require(x.value()->payload->facet_geometry.size()==x.value()->payload->facets.size(),"facet geometry count");for(const auto&f:x.value()->payload->facets){const auto&g=x.value()->payload->facet_geometry[f.id.value_for_debug()];require(g.facet==f.id&&g.operand==f.operand,"facet geometry binding");require(g.ring3.size()==f.ring.size()&&g.ring2.size()==f.ring.size()&&g.edges.size()==f.ring.size()&&g.vertex_fans.size()==f.ring.size(),"facet geometry ring alignment");require(g.triangles.size()==f.triangles.size(),"facet geometry triangle alignment");}require(x.value()->payload->edges.size()==6,"edges");require(x.value()->payload->shells.size()==1,"shell");require(x.value()->payload->operands[0].bounds.has_value(),"operand bounds");require(x.value()->payload->evidence.size()==14,"artifact evidence summaries");require(x.value()->report.passed()&&!x.value()->report.evidence.empty(),"verified evidence");}
template<class T,class I>void malformed(){auto a=tetra<T,I>(),b=fv_surface_mesh<T,I>{};a.faces[0][0]=I(99);auto r=registry();auto c=context(a,b,r);auto x=validate_operands(*c);require(!x.has_value(),"bad index rejected");require(x.error().code==boolean_error_code::input_contract_error,"input error");}
template<class T,class I>void polygon(){auto a=cube<T,I>(),b=fv_surface_mesh<T,I>{};auto r=registry();auto c=context(a,b,r);auto x=validate_operands(*c);require(x.has_value(),"quad cube validates");require(x.value()->payload->facets.size()==6,"polygon facets");for(const auto&f:x.value()->payload->facets)require(f.triangles.size()==2,"exact quad triangulation");}
template<class T,class I>void cavity(){auto a=box<T,I>(T(0),T(4));append(a,box<T,I>(T(1),T(2)),true);fv_surface_mesh<T,I>b;auto r=registry();auto c=context(a,b,r);auto x=validate_operands(*c);if(!x.has_value())throw std::runtime_error("nested cavity: "+render_error(x.error()));require(x.value()->payload->shells.size()==2,"two nested shells");std::size_t cavities=0;for(const auto&s:x.value()->payload->shells)if(s.contribution==shell_contribution::cavity_boundary){++cavities;require(s.depth==1&&s.orientation==shell_orientation::inward,"cavity semantics");}require(cavities==1,"one cavity");auto bad=box<T,I>(T(0),T(4));append(bad,box<T,I>(T(1),T(2)));auto c2=context(bad,b,r);auto y=validate_operands(*c2);require(!y.has_value()&&y.error().subcode==static_cast<std::uint32_t>(input_validation_subcode::orientation_mismatch),"bad cavity orientation rejected");}
template<class T,class I>void shell_contacts(){for(T shift:{T(1),T(2)}){auto a=box<T,I>(T(0),T(2));append(a,box<T,I>(shift,shift+T(2)));fv_surface_mesh<T,I>b;auto r=registry();auto c=context(a,b,r);auto x=validate_operands(*c);require(!x.has_value(),shift==T(1)?"crossing shells rejected":"touching shells rejected");require(x.error().subcode==static_cast<std::uint32_t>(input_validation_subcode::shell_contact),"shell contact code");}}
template<class T,class I>void difficult_polygons(){for(bool collinear:{false,true}){auto a=prism<T,I>(collinear);fv_surface_mesh<T,I>b;auto r=registry();auto c=context(a,b,r);auto x=validate_operands(*c);require(x.has_value(),collinear?"collinear polygon validates":"concave polygon validates");}}
template<class T,class I>auto context_with_options(fv_surface_mesh<T,I>&a,fv_surface_mesh<T,I>&b,std::shared_ptr<verifier_registry>r,boolean_options options){std::shared_ptr<const exact_kernel_services<T>>k=std::make_shared<exact_kernel<T>>();std::shared_ptr<const verifier_service>v=r;auto c=make_boolean_context(a,b,operation::regularized_union,std::move(options),k,v);require(c.has_value(),"limited context");return std::move(c.value());}
template<class T,class I>void exact_bit_limits(){auto a=tetra<T,I>(),b=fv_surface_mesh<T,I>{};auto r=registry();auto baseline=context(a,b,r);require(validate_operands(*baseline).has_value(),"exact bit baseline");const auto bits=baseline->accountant().used(resource_kind::exact_number_bits);require(bits>0,"exact bit charge");boolean_options exact;exact.resources.exact_number_bits={false,bits};auto at=context_with_options(a,b,r,exact);require(validate_operands(*at).has_value()&&at->accountant().used(resource_kind::exact_number_bits)==bits,"exact bit exact limit");boolean_options spare;spare.resources.exact_number_bits={false,bits+1};auto above=context_with_options(a,b,r,spare);require(validate_operands(*above).has_value()&&above->accountant().used(resource_kind::exact_number_bits)==bits,"exact bit limit plus one");boolean_options short_limit;short_limit.resources.exact_number_bits={false,bits-1};auto below=context_with_options(a,b,r,short_limit);auto rejected=validate_operands(*below);require(!rejected.has_value()&&rejected.error().code==boolean_error_code::resource_limit&&below->accountant().used(resource_kind::exact_number_bits)==0,"exact bit limit minus one rolls back");}
template<class T,class I>void duplicate_facets(){for(bool reverse:{false,true}){auto a=tetra<T,I>(),b=fv_surface_mesh<T,I>{};auto duplicate=a.faces[0];std::rotate(duplicate.begin(),duplicate.begin()+1,duplicate.end());if(reverse)std::reverse(duplicate.begin(),duplicate.end());a.faces.push_back(duplicate);auto r=registry();auto c=context(a,b,r);auto x=validate_operands(*c);require(!x.has_value()&&x.error().subcode==static_cast<std::uint32_t>(input_validation_subcode::duplicate_facet),"rotated/reversed duplicate facet rejected");}}
template<class T,class I>void linear_degenerate_support_scan(){fv_surface_mesh<T,I>a,b;constexpr std::size_t count=12;for(std::size_t i=0;i<count;++i)a.vertices.push_back({static_cast<T>(i),T(0),T(0)});a.faces.emplace_back();for(std::size_t i=0;i<count;++i)a.faces[0].push_back(static_cast<I>(i));auto r=registry();auto c=context(a,b,r);performance_collector collector;status_or<std::shared_ptr<const published_artifact<validated_operands<T,I>>>>x=make_error(boolean_error_code::internal_invariant_error,boolean_stage::input_validation,"not_run");{performance_scope scope(&collector,boolean_stage::input_validation,performance_role::producer);x=validate_operands(*c);}require(!x.has_value()&&x.error().subcode==static_cast<std::uint32_t>(input_validation_subcode::degenerate_facet),"collinear facet rejected");const auto attempts=collector.snapshot()->stage(boolean_stage::input_validation).producer.value(performance_counter::support_plane_constructions);require(attempts==count-2,"support triple scan is linear");}
template<class T,class I>void sparse_candidate_counters(){auto a=box<T,I>(T(0),T(1)),b=fv_surface_mesh<T,I>{};for(I i=1;i<I(8);++i)append(a,box<T,I>(T(i*4),T(i*4+1)));auto r=registry();auto c=context(a,b,r);performance_collector collector;status_or<std::shared_ptr<const published_artifact<validated_operands<T,I>>>>x=make_error(boolean_error_code::internal_invariant_error,boolean_stage::input_validation,"not_run");{performance_scope scope(&collector,boolean_stage::input_validation,performance_role::producer);x=validate_operands(*c);}require(x.has_value(),"sparse boxes validate");const auto counters=collector.snapshot()->stage(boolean_stage::input_validation).producer;const auto facets=x.value()->payload->operands[0].facets.size();const auto logical=facets*(facets-1)/2;const auto candidates=counters.value(performance_counter::self_embedding_candidate_pairs);require(candidates<logical,"facet exact work is candidate scaled");require(counters.value(performance_counter::exact_facet_pair_tests)==candidates,"every facet candidate tested exactly");require(counters.value(performance_counter::ring_edge_candidate_pairs)>0,"ring candidates counted");require(counters.value(performance_counter::exact_ring_edge_tests)<=counters.value(performance_counter::ring_edge_candidate_pairs),"ring exact tests are candidate bounded");require(counters.value(performance_counter::ear_candidates)>0,"incremental ears counted");}
int main(){try{valid<float,std::uint32_t>();valid<float,std::uint64_t>();valid<double,std::uint32_t>();valid<double,std::uint64_t>();polygon<float,std::uint32_t>();polygon<double,std::uint64_t>();cavity<double,std::uint32_t>();shell_contacts<double,std::uint32_t>();difficult_polygons<double,std::uint32_t>();malformed<float,std::uint32_t>();malformed<double,std::uint64_t>();exact_bit_limits<double,std::uint32_t>();duplicate_facets<double,std::uint32_t>();linear_degenerate_support_scan<double,std::uint32_t>();sparse_candidate_counters<double,std::uint32_t>();std::cout<<"PASS input topology\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL "<<e.what()<<'\n';return 1;}}
