#include "MeshBooleanBroadPhaseFixtures.h"
#include <algorithm>
#include <cmath>
#include <iostream>
#include <limits>
#include <random>
using namespace broad_test;
template<class T,class I>void generated(){std::uint64_t state=0x9e3779b97f4a7c15ULL;auto next=[&](){state=state*6364136223846793005ULL+1442695040888963407ULL;return state;};for(unsigned trial=0;trial<20;++trial){T alo=T(next()%8),blo=T(next()%8);auto a=box<T,I>(alo,alo+T(2)),b=box<T,I>(blo,blo+T(2));auto r=broad_test::registry();auto c=context(a,b,r);auto x=enumerate_broad_phase_candidates(*c);require(x.has_value(),"generated stage");auto expected=exhaustive(*x.value()->payload->validated->payload);require(expected.size()==x.value()->payload->candidates.size(),"generated exhaustive size");for(std::size_t i=0;i<expected.size();++i)require(expected[i]==x.value()->payload->candidates[i].key,"generated exhaustive keys");auto first=x.value()->payload->canonical_candidate_bytes;auto r2=broad_test::registry();auto c2=context(a,b,r2);auto y=enumerate_broad_phase_candidates(*c2);require(y.has_value()&&first==y.value()->payload->canonical_candidate_bytes,"semantic determinism");}}
void self_query_oracle(){std::uint64_t state=0x243f6a8885a308d3ULL;auto next=[&](){state=state*6364136223846793005ULL+1442695040888963407ULL;return state;};const auto owner=make_context_owner_token();for(std::size_t trial=0;trial<64;++trial){const std::size_t count=3+next()%45;std::vector<bounded_feature_view> features;features.reserve(count);for(std::size_t i=0;i<count;++i){auto interval=[&](){const std::int64_t a=static_cast<std::int64_t>(next()%31)-15;const std::int64_t b=a+static_cast<std::int64_t>(next()%5);return exact_interval{exact_scalar(a),exact_scalar(b),true,true};};const bool fallback=(next()%11)==0;features.push_back({{owner,91,i},fallback?bound_source_kind::exhaustive_fallback:bound_source_kind::exact_box,{interval(),interval(),interval()},fallback?bound_fallback_reason::missing_exact_bound:bound_fallback_reason::caller_requested});}std::vector<std::pair<std::uint64_t,std::uint64_t>> expected;for(std::size_t i=0;i<count;++i)for(std::size_t j=i+1;j<count;++j)if(features[i].source==bound_source_kind::exhaustive_fallback||features[j].source==bound_source_kind::exhaustive_fallback||exact_bounds_overlap(features[i].bound,features[j].bound))expected.push_back({i,j});std::shuffle(features.begin(),features.end(),std::mt19937(static_cast<std::uint32_t>(next())));auto actual=enumerate_bounded_feature_self(features);require(actual.has_value(),"generated self query");require(actual.value().size()==expected.size(),"self query exhaustive size");for(std::size_t i=0;i<expected.size();++i)require(actual.value()[i].first.canonical_rank==expected[i].first&&actual.value()[i].second.canonical_rank==expected[i].second,"self query exhaustive pair");}}
template<class T,class I>void exact_case(T alo,T ahi,T blo,T bhi){auto a=box<T,I>(alo,ahi),b=box<T,I>(blo,bhi);auto r=broad_test::registry();auto c=context(a,b,r);auto result=enumerate_broad_phase_candidates(*c);require(result.has_value(),"adversarial stage");const auto expected=exhaustive(*result.value()->payload->validated->payload);require(expected.size()==result.value()->payload->candidates.size(),"adversarial exhaustive size");for(std::size_t i=0;i<expected.size();++i)require(expected[i]==result.value()->payload->candidates[i].key,"adversarial exhaustive key");}
template<class T,class I>void adversarial_bounds(){const T one=T(1),two=T(2);exact_case<T,I>(T(0),one,one,two);exact_case<T,I>(T(0),one,std::nextafter(one,two),two);exact_case<T,I>(T(-0.0),one,T(0),one);const T d=std::numeric_limits<T>::denorm_min();exact_case<T,I>(T(0),d*T(4),d*T(4),d*T(8));const T large=std::numeric_limits<T>::max()/T(4);exact_case<T,I>(large,T(2)*large,T(2)*large,T(3)*large);}
template<class T,class I>void permutations_and_threads(){auto a=box<T,I>(T(0),T(1)),b=box<T,I>(T(0.5),T(1.5));for(unsigned i=1;i<4;++i){append(a,box<T,I>(T(3*i),T(3*i+1)));append(b,box<T,I>(T(3*i)+T(0.5),T(3*i)+T(1.5)));}std::vector<std::uint8_t>reference;for(std::uint32_t threads:{1U,2U,4U}){auto aa=threads==2?permuted<T,I>(a):a;auto bb=threads==4?permuted<T,I>(b):b;auto r=broad_test::registry();auto c=context_with_threads(aa,bb,r,threads);auto result=enumerate_broad_phase_candidates(*c);require(result.has_value(),"permutation/thread stage");const auto expected=exhaustive(*result.value()->payload->validated->payload);require(expected.size()==result.value()->payload->candidates.size(),"permutation/thread exhaustive");if(reference.empty())reference=result.value()->payload->canonical_candidate_bytes;else require(reference==result.value()->payload->canonical_candidate_bytes,"permutation/thread candidate bytes");require(result.value()->payload->implementation_statistics.build_comparisons>0,"build comparisons counted");}}
void verifier_admission_and_evidence(){
  auto a=box<double,std::uint32_t>(0.0,1.0),b=box<double,std::uint32_t>(0.5,1.5);
  auto registry=broad_test::registry();auto c=context(a,b,registry);
  auto result=enumerate_broad_phase_candidates(*c);require(result.has_value(),"broad verifier resource fixture");
  const auto tag=candidate_stream_type_tag+(static_cast<std::uint64_t>(coordinate_tag::binary64)<<8)+static_cast<std::uint64_t>(index_tag::uint32);
  auto spec=registry->specification(artifact_slot::candidate_stream,tag,candidate_stream_schema,verification_level::mandatory);require(spec.has_value(),"broad mandatory specification");
  artifact_view view{c->owner(),artifact_slot::candidate_stream,tag,candidate_stream_schema,1,result.value()->artifact_digest,result.value()->payload,result.value()->payload.get()};
  const auto&artifact=*result.value()->payload;const auto facets=artifact.validated->payload->facets.size();const auto work=4*facets+artifact.candidates.size()+artifact.canonical_candidate_bytes.size();const auto scratch=1024*(facets+artifact.candidates.size())+4*(artifact.canonical_candidate_bytes.size()+artifact.artifact_bytes.size());
  const std::array<std::pair<resource_kind,std::uint64_t>,2> resources{{{resource_kind::verifier_work,work},{resource_kind::verifier_scratch_bytes,scratch}}};
  for(const auto&entry:resources){require(entry.second>0,"broad verifier resource measured");auto run=[&](std::uint64_t limit){resource_policy policy;if(entry.first==resource_kind::verifier_work)policy.verifier_work={false,limit};else policy.verifier_scratch_bytes={false,limit};resource_accountant accountant(policy);verification_environment_view env{c->owner(),c->replay().setup,c->contract().selected_operation(),&c->options(),coordinate_tag::binary64,index_tag::uint32,&c->kernel(),{},&accountant,[]{return false;}};auto checked=registry->verify(view,spec.value(),env);require(accountant.used(resource_kind::verifier_work)==0&&accountant.used(resource_kind::verifier_scratch_bytes)==0,"broad verifier resource rollback");return checked;};auto exact=run(entry.second);require(exact.has_value()&&exact.value().passed(),"broad verifier exact admission");auto short_result=run(entry.second-1);require(!short_result.has_value()&&short_result.error().code==boolean_error_code::resource_limit,"broad verifier one-under admission");}
  auto stale=view;stale.artifact_digest.bytes[0]^=1;resource_accountant accountant(resource_policy{});verification_environment_view env{c->owner(),c->replay().setup,c->contract().selected_operation(),&c->options(),coordinate_tag::binary64,index_tag::uint32,&c->kernel(),{},&accountant,[]{return false;}};auto rejected=registry->verify(stale,spec.value(),env);require(rejected.has_value()&&!rejected.value().passed()&&rejected.value().results.size()==spec.value().required_invariants.size()&&rejected.value().results.front().status==check_status::failed,"stale broad artifact binding rejected");
  auto report=result.value()->report;report.evidence.front().schema++;require(!validate_verification_report(report).has_value(),"stale broad evidence schema rejected");report=result.value()->report;report.evidence.front().exact_payload.push_back(0);require(!validate_verification_report(report).has_value(),"stale broad evidence digest rejected");
}
int main(){try{generated<float,std::uint32_t>();generated<double,std::uint64_t>();self_query_oracle();adversarial_bounds<float,std::uint32_t>();adversarial_bounds<double,std::uint64_t>();permutations_and_threads<float,std::uint32_t>();permutations_and_threads<double,std::uint64_t>();verifier_admission_and_evidence();std::cout<<"PASS broad phase properties\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL "<<e.what()<<'\n';return 1;}}
