#include "MeshBooleanGlobalArrangementFixtures.h"
#include <iostream>
using namespace arrangement_test;
int main(){try{
  auto r=arrangement_test::registry();auto a=cube<double,std::uint32_t>(),b=cube<double,std::uint32_t>();translate(b,3,0,0);boolean_options one;one.execution.max_threads=1;auto c1=context(a,b,r,one);auto x=build_global_arrangement(*c1);require(x.has_value(),"single schedule");boolean_options many;many.execution.max_threads=4;auto c2=context(a,b,r,many);auto y=build_global_arrangement(*c2);require(y.has_value(),"parallel schedule");require(x.value()->payload->canonical_bytes==y.value()->payload->canonical_bytes,"schedule canonical");structural_oracle(*x.value()->payload);
  cancellation_source stop;auto cc=context(a,b,r,boolean_options{},&stop);stop.cancel();auto cancelled=build_global_arrangement(*cc);require(!cancelled.has_value()&&cancelled.error().code==boolean_error_code::resource_limit&&cc->artifacts().latest_generation(artifact_slot::arrangement_complex)==0,"cancel rollback");
  auto crossing_a=cube<double,std::uint32_t>(),crossing_b=cube<double,std::uint32_t>();translate(crossing_b,0.5,0.5,0.5);auto crossing_context=context(crossing_a,crossing_b,r);auto crossing=build_global_arrangement(*crossing_context);if(!crossing.has_value())throw std::runtime_error(render_error(crossing.error()));structural_oracle(*crossing.value()->payload);require(!crossing.value()->payload->seams.empty(),"transverse seams retained");
  auto same_a=cube<double,std::uint32_t>(),same_b=cube<double,std::uint32_t>();auto same_context=context(same_a,same_b,r);auto same=build_global_arrangement(*same_context);if(!same.has_value())throw std::runtime_error(render_error(same.error()));structural_oracle(*same.value()->payload);require(!same.value()->payload->coincident_groups.empty(),"coincident sheets retained");for(const auto&group:same.value()->payload->coincident_groups)require(group.members.size()==2,"separate coincidence members");
  auto partial_a=cube<double,std::uint32_t>(),partial_b=cube<double,std::uint32_t>();translate(partial_b,0.5,0,0);auto partial_context=context(partial_a,partial_b,r);auto partial=build_global_arrangement(*partial_context);if(!partial.has_value())throw std::runtime_error(render_error(partial.error()));structural_oracle(*partial.value()->payload);require(!partial.value()->payload->coincident_groups.empty(),"partial coplanar common atoms");
  boolean_options limited;limited.resources.probe_descriptors={false,1};auto limited_context=context(a,b,r,limited);auto over=build_global_arrangement(*limited_context);require(!over.has_value()&&over.error().code==boolean_error_code::resource_limit&&limited_context->artifacts().latest_generation(artifact_slot::arrangement_complex)==0,"probe resource rollback");
  std::cout<<"ok\n";
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
