#include "MeshBooleanSelectionFixtures.h"
#include <iostream>
using namespace selection_test;
template<class T,class I>
static void qualification(){
  auto a=input_test::box<T,I>(T(0),T(1)),b=input_test::box<T,I>(T(3),T(4));
  boolean_options one;one.execution.max_threads=1;auto c1=context(a,b,selection_test::registry(),operation::regularized_union,one);auto x=select_boolean_boundary(*c1);require(x.has_value(),"selection single-thread schedule");
  boolean_options many;many.execution.max_threads=4;auto c4=context(a,b,selection_test::registry(),operation::regularized_union,many);auto y=select_boolean_boundary(*c4);require(y.has_value(),"selection multi-thread schedule");require(x.value()->payload->canonical_bytes==y.value()->payload->canonical_bytes,"selection schedule determinism");

  auto translated_a=a,translated_b=b;translate(translated_a,T(-8),T(4),T(2));translate(translated_b,T(-8),T(4),T(2));auto translated_context=context(translated_a,translated_b,selection_test::registry());auto translated=select_boolean_boundary(*translated_context);require(translated.has_value(),"translated selection");require(decision_histogram(*translated.value()->payload)==decision_histogram(*x.value()->payload)&&translated.value()->payload->patches.size()==x.value()->payload->patches.size(),"translation-equivariant selection");
  auto swapped_context=context(b,a,selection_test::registry());auto swapped=select_boolean_boundary(*swapped_context);require(swapped.has_value(),"operand-swapped union");require(decision_histogram(*swapped.value()->payload)==decision_histogram(*x.value()->payload)&&swapped.value()->payload->patches.size()==x.value()->payload->patches.size(),"commutative union selection");

  cancellation_source stop;auto cancelled_context=context(a,b,selection_test::registry(),operation::regularized_union,boolean_options{},&stop);stop.cancel();auto cancelled=select_boolean_boundary(*cancelled_context);require(!cancelled.has_value()&&cancelled.error().code==boolean_error_code::resource_limit,"selection cancellation category");require(cancelled_context->artifacts().latest_generation(artifact_slot::selected_exact_boundary)==0,"selection cancellation rollback");

  const auto&base=*x.value()->payload;using member=resource_limit resource_policy::*;
  const std::array<std::tuple<member,resource_kind,std::uint64_t>,8> limits{{
    {&resource_policy::selection_decisions,resource_kind::selection_decisions,base.decisions.size()},
    {&resource_policy::selected_patches,resource_kind::selected_patches,base.patches.size()},
    {&resource_policy::selected_cycles,resource_kind::selected_cycles,base.cycles.size()},
    {&resource_policy::selected_halfedges,resource_kind::selected_halfedges,base.halfedges.size()},
    {&resource_policy::selected_edges,resource_kind::selected_edges,base.edges.size()},
    {&resource_policy::selected_vertices,resource_kind::selected_vertices,base.vertices.size()},
    {&resource_policy::selected_vertex_occurrences,resource_kind::selected_vertex_occurrences,base.vertex_occurrences.size()},
    {&resource_policy::selection_provenance,resource_kind::selection_provenance,base.certificate.provenance_uses}}};
  for(const auto&entry:limits){const auto field=std::get<0>(entry);const auto kind=std::get<1>(entry);const auto required=std::get<2>(entry);require(required>0,"selection resource fixture");boolean_options exact;exact.resources.*field={false,required};auto exact_context=context(a,b,selection_test::registry(),operation::regularized_union,exact);auto accepted=select_boolean_boundary(*exact_context);require(accepted.has_value(),"selection exact resource limit");require(exact_context->accountant().used(kind)==required,"selection exact resource charge");boolean_options short_limit;short_limit.resources.*field={false,required-1};auto short_context=context(a,b,selection_test::registry(),operation::regularized_union,short_limit);auto rejected=select_boolean_boundary(*short_context);require(!rejected.has_value()&&rejected.error().code==boolean_error_code::resource_limit,"selection one-under resource rejection");require(short_context->artifacts().latest_generation(artifact_slot::selected_exact_boundary)==0&&short_context->accountant().used(kind)==0,"selection resource rollback");}

  auto equal_a=input_test::box<T,I>(T(0),T(1)),equal_b=equal_a;
  for(auto op:{operation::regularized_union,operation::regularized_intersection,operation::a_minus_b,operation::b_minus_a,operation::symmetric_difference}){auto equal_context=context(equal_a,equal_b,selection_test::registry(),op,boolean_options{});auto equal=select_boolean_boundary(*equal_context);require(equal.has_value(),"equal-solid selection identity");selection_oracle(*equal.value()->payload);const bool retained=op==operation::regularized_union||op==operation::regularized_intersection;require(equal.value()->payload->patches.size()==(retained?6U:0U),"equal-solid Boolean identity");for(const auto&p:equal.value()->payload->patches)require(p.provenance.size()==2&&p.representative==*std::min_element(p.provenance.begin(),p.provenance.end()),"canonical coincidence representative");}
}
int main(){try{const auto operations={operation::regularized_union,operation::regularized_intersection,operation::a_minus_b,operation::b_minus_a,operation::symmetric_difference};for(auto op:operations)for(unsigned n=0;n<4;++n)for(unsigned p=0;p<4;++p){occupancy_pair negative{bool(n&2),bool(n&1)},positive{bool(p&2),bool(p&1)};operation_contract c(op);const bool expected_negative=oracle_occupied(op,negative),expected_positive=oracle_occupied(op,positive);require(c.occupied(negative.in_a,negative.in_b)==expected_negative,"independent negative truth");require(c.occupied(positive.in_a,positive.in_b)==expected_positive,"independent positive truth");const auto expected=oracle_decision(op,negative,positive);const int orientation=c.patch_orientation(negative,positive);require((expected==patch_decision_kind::select_preserved&&orientation==1)||(expected==patch_decision_kind::select_reversed&&orientation==-1)||((expected==patch_decision_kind::discard_exterior||expected==patch_decision_kind::discard_internal)&&orientation==0),"independent selection row");}
auto run=[&](auto scalar,auto index){using T=decltype(scalar);using I=decltype(index);for(auto op:operations){run_analytic_selection_case<T,I>(selection_test::registry(),T(0),T(1),T(3),T(4),op);run_analytic_selection_case<T,I>(selection_test::registry(),T(0),T(3),T(1),T(2),op);run_analytic_selection_case<T,I>(selection_test::registry(),T(0),T(1),T(0),T(1),op);if(op==operation::symmetric_difference)run_nonmanifold_selection_case<T,I>(selection_test::registry(),T(0),T(2),T(1),T(3),op);else run_analytic_selection_case<T,I>(selection_test::registry(),T(0),T(2),T(1),T(3),op);run_analytic_selection_case<T,I>(selection_test::registry(),T(0),T(1),T(1),T(2),op);}};
 run(float{},std::uint32_t{});run(float{},std::uint64_t{});run(double{},std::uint32_t{});run(double{},std::uint64_t{});qualification<double,std::uint32_t>();std::cout<<"ok\n";}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
