#include "YgorMeshesBooleanBounded.h"
#include "YgorMeshesBooleanBounded/CanonicalBytes.h"
#include "YgorMeshesBooleanBounded/Context.h"
#include "YgorMeshesBooleanBounded/ContextVerifier.h"
#include "YgorMeshesBooleanBounded/Identity.h"
#include "YgorMeshesBooleanBounded/InvocationSourcesVerifier.h"
#include "YgorMeshesBooleanBounded/Resources.h"
#include "YgorMeshesBooleanBounded/Sha256.h"
#include "YgorMeshesBooleanBounded/SymbolicPolicy.h"
#include "YgorMeshesBooleanBounded/Transaction.h"

#include <cfenv>
#include <cstdint>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <vector>

namespace bounded = ygor::mesh_boolean::bounded;
namespace {
void require(bool condition,const char*message){if(!condition)throw std::runtime_error(message);}
void test_sha256(){std::vector<std::uint8_t> empty;require(bounded::sha256::digest(empty).hex()=="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","SHA-256 empty vector");std::vector<std::uint8_t>abc{'a','b','c'};require(bounded::sha256::digest(abc).hex()=="ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad","SHA-256 abc vector");bounded::sha256 split;for(auto c:abc)split.update(&c,1);require(split.finish()==bounded::sha256::digest(abc),"SHA-256 split update");}
void test_codec(){bounded::canonical_writer w;w.u16(0x1234);w.u64(0x0102030405060708ULL);w.boolean(true);w.floating(-0.0);auto bytes=w.take();require(bytes[0]==0x34&&bytes[1]==0x12,"little endian codec");bounded::canonical_reader r(bytes);std::uint16_t a=0;std::uint64_t b=0;bool c=false;double d=0;require(r.u16(a)&&r.u64(b)&&r.boolean(c)&&r.floating(d)&&r.complete(),"codec decode");require(a==0x1234&&b==0x0102030405060708ULL&&c&&std::signbit(d),"codec values");}
void test_truth(){auto table=bounded::materialize_truth_table();require(table.cells.size()==80,"truth table size");for(std::uint8_t op=1;op<=5;++op)for(std::uint8_t bits=0;bits<16;++bits){const auto &c=table.cells[(op-1)*16+bits];auto expected=bounded::evaluate_truth(static_cast<boolean_operation>(op),{bool(bits&1),bool(bits&2),bool(bits&4),bool(bits&8)});require(c.retain==expected.retain&&c.orientation==expected.orientation,"truth table cell");}require(bounded::swap_operands(boolean_operation::a_minus_b)==boolean_operation::b_minus_a,"operation remap");auto symbolic=bounded::materialize_symbolic_policy();require(bounded::verify_symbolic_policy(symbolic)&&symbolic.rules.size()==bounded::symbolic_rule_count,"symbolic policy totality");for(std::uint64_t ordinal=0;ordinal<bounded::symbolic_rule_count;++ordinal){const auto key=bounded::symbolic_rule_key_from_ordinal(ordinal);require(bounded::valid_symbolic_rule_key(key)&&bounded::symbolic_rule_ordinal(key)==ordinal,"symbolic key ordinal round trip");const auto exchanged_key=bounded::exchange_symbolic_rule_key(key);require(bounded::exchange_symbolic_rule_key(exchanged_key)==key,"symbolic key operand exchange involution");const auto &rule=symbolic.rules[ordinal];require(rule.key==key&&rule.exchanged_key==exchanged_key&&rule.exchange_rule_ordinal==bounded::symbolic_rule_ordinal(exchanged_key),"symbolic rule lookup and exchange");const auto &exchanged=symbolic.rules[rule.exchange_rule_ordinal];require(exchanged.exchange_rule_ordinal==ordinal&&exchanged.exchanged_key==key,"symbolic rule exchange round trip");require(exchanged.feature_priority==rule.feature_priority&&exchanged.contact_class==rule.contact_class&&exchanged.expected_disposition==rule.expected_disposition&&exchanged.owner_rank_eligible==rule.owner_rank_eligible&&exchanged.occurrence_separation_required==rule.occurrence_separation_required,"symbolic exchange invariant fields");if(rule.conceptual_offset!=bounded::symbolic_offset_disposition::coincident)require(static_cast<std::int8_t>(exchanged.conceptual_offset)==-static_cast<std::int8_t>(rule.conceptual_offset),"symbolic exchange conceptual order");require(exchanged.crossing_contribution==-rule.crossing_contribution,"symbolic exchange crossing contribution");}auto mutated_rule=symbolic;mutated_rule.rules.front().feature_priority^=1U;require(!bounded::verify_symbolic_policy(mutated_rule),"symbolic rule mutation rejected");auto mutated_bytes=symbolic;mutated_bytes.bytes.back()^=1U;mutated_bytes.digest=bounded::sha256::digest(mutated_bytes.bytes);require(!bounded::verify_symbolic_policy(mutated_bytes),"symbolic byte mutation rejected");}
template<class T,class I>void test_sources(){fv_surface_mesh<T,I>a,b;a.vertices.emplace_back(T(-0.0),T(1),std::numeric_limits<T>::infinity());a.faces.push_back({I(7),I(7)});a.vertex_normals.emplace_back(T(9),T(9),T(9));a.metadata["ignored"]="one";auto first=bounded::capture_invocation_sources(a,b);require(first.has_value()&&bounded::verify_invocation_sources(*first.value()),"source capture");a.vertex_normals.clear();a.vertex_colours.push_back(42);a.metadata["ignored"]="two";auto second=bounded::capture_invocation_sources(a,b);require(second.has_value()&&first.value()->digest==second.value()->digest,"ignored fields invariant");require(first.value()->a.coordinate_bits().front()!=0,"signed zero bits retained");a.faces[0].push_back(I(8));auto third=bounded::capture_invocation_sources(a,b);require(third.has_value()&&third.value()->digest!=first.value()->digest,"source order content digest");}
struct test_transaction_participant final : bounded::transaction_participant {
    bool throw_on_prepare = false;
    bool prepared = false;
    bool published = false;
    bool prepare() override {
        if (throw_on_prepare) throw std::runtime_error("prepare failure");
        prepared = true;
        return true;
    }
    void commit() noexcept override { published = true; }
    void rollback() noexcept override { prepared = false; published = false; }
};
void test_identity_resources_transaction(){struct tag{};static_assert(!std::is_convertible_v<bounded::strong_id<tag>,std::uint64_t>);auto ids=bounded::publish_canonical_ids<tag,int>({9,2,5});require(ids&&(*ids)[0].first==2&&(*ids)[0].second.ordinal()==0,"canonical IDs");require(!bounded::publish_canonical_ids<tag,int>({1,1}),"duplicate canonical key");resource_policy p=resource_policy::conservative_defaults();p.temporary_bytes={5,10};p.budget_commits={1,1};bounded::resource_manager manager(p);auto reservation=manager.reserve(bounded::resource_kind::temporary_bytes,10);require(bool(reservation)&&!manager.reserve(bounded::resource_kind::temporary_bytes,1),"resource hard limit");reservation->release();require(manager.reserve(bounded::resource_kind::temporary_bytes,1).has_value(),"resource release");auto budget_limit=manager.reserve(bounded::resource_kind::budget_commits,1);require(budget_limit&&budget_limit->commit(1)&&!manager.reserve(bounded::resource_kind::budget_commits,1),"component resource exact hard boundary");bool cancelled=true;bounded::resource_cancellation_checkpoint checkpoint{&cancelled,[](const void*state)noexcept{return *static_cast<const bool*>(state);}};require(!manager.reserve(bounded::resource_kind::precision_trace_nodes,1,checkpoint),"cancelled resource checkpoint has zero reservation");bounded::stage_transaction tx;test_transaction_participant participant;require(tx.open()&&tx.enlist(participant)&&tx.begin_join()&&tx.begin_verify()&&tx.ready()&&participant.prepared&&tx.commit()&&participant.published,"transaction commit protocol");bounded::stage_transaction rollback;require(rollback.open(),"transaction open");rollback.rollback();require(rollback.state()==bounded::transaction_state::rolled_back,"transaction rollback");bounded::stage_transaction exceptional;test_transaction_participant first;test_transaction_participant failing;failing.throw_on_prepare=true;require(exceptional.open()&&exceptional.enlist(first)&&exceptional.enlist(failing)&&exceptional.begin_join()&&exceptional.begin_verify()&&!exceptional.ready()&&!first.prepared&&!first.published&&exceptional.state()==bounded::transaction_state::rolled_back,"transaction exception rollback has zero publication");}
void test_options_cancellation(){bounded_boolean_options<double> o;o.tolerance=1;o.input_precision_a=2;require(!bounded::normalize_options(o).has_value(),"precision exceeds tolerance");o.input_precision_a=0;o.output.preserve_public_metadata=true;require(!bounded::normalize_options(o).has_value(),"metadata preservation rejected");bounded_boolean_cancellation_source source;auto token=source.token();source.request_cancel(17);source.request_cancel(18);require(token.cancellation_requested()&&token.reason()==17,"first cancellation reason");}
void test_public_gate(){fv_surface_mesh<double,std::uint32_t>a,b;bounded_boolean_options<double>o;const int old=std::fegetround();auto result=bounded_boolean(a,b,boolean_operation::set_union,o);require(!result.has_value(),"component 04 gate");if(result.error()->category!=bounded_boolean_error_category::result_geometry_not_validated)throw std::runtime_error(result.error()->summary);require(result.error()->subcode==2004&&result.error()->component==4,"component 04 gate subcode");require(result.error()->context_digest!=bounded_boolean_digest{},"precision context digest published to next gate");require(std::fegetround()==old,"floating environment restored");}
void test_context_handshake(){fv_surface_mesh<double,std::uint32_t>a,b;bounded_boolean_options<double>o;o.tolerance=1;auto pending=bounded::build_pending_invocation(a,b,boolean_operation::intersection,o);require(pending.has_value(),"pending invocation");auto replay=bounded::decode_replay_input(pending.value()->replay_bytes);require(replay.has_value()&&replay.value()->operation==boolean_operation::intersection,"replay decode");auto truncated=pending.value()->replay_bytes;truncated.pop_back();require(!bounded::decode_replay_input(truncated).has_value(),"replay truncation");bounded::precision_bootstrap_record<double> precision;precision.machine_floor=0.5;precision.source_digest=pending.value()->sources.digest;auto context=bounded::finalize_context(std::move(*pending.value()),precision);require(context.has_value()&&bounded::verify_context(*context.value()),"precision context handshake");}
}
int main(){try{test_sha256();test_codec();test_truth();test_sources<float,std::uint32_t>();test_sources<float,std::uint64_t>();test_sources<double,std::uint32_t>();test_sources<double,std::uint64_t>();test_identity_resources_transaction();test_options_cancellation();test_context_handshake();test_public_gate();std::cout<<"Component 01 regression tests passed\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
