#include "YgorMeshesExactKernel.h"
#include "YgorMeshesBooleanPerformance.h"
#include <algorithm>
#include <atomic>
#include <stdexcept>
#if defined(__FAST_MATH__)
#error "Exact kernel must not be compiled with fast-math"
#endif
#if defined(__FINITE_MATH_ONLY__) && __FINITE_MATH_ONLY__
#error "Exact kernel must not assume finite-only arithmetic"
#endif
namespace ygor { namespace mesh_boolean {
exact_sign substitute_defining_relation(const defining_relation&r,const exact_point3&p){
  return (r.coefficients[0]*p.x+r.coefficients[1]*p.y+
          r.coefficients[2]*p.z+r.coefficients[3]).sign();
}
bool defining_relation_satisfied(const defining_relation&r,const exact_point3&p){
  return r.formula_version==1&&substitute_defining_relation(r,p)==r.expected;
}
namespace{exact_sign sg(const exact_scalar&x){return x.sign();}exact_scalar ri(const big_int&x){return exact_rational(x,big_uint(1));}exact_scalar eval(const exact_plane3&p,const exact_point3&q){auto v=ri(p.a)*q.x+ri(p.b)*q.y+ri(p.c)*q.z+ri(p.d);return p.oriented==orientation_parity::agree?v:v.negated();}bool z(const exact_vector2&v){return v.x.is_zero()&&v.y.is_zero();}bool z(const exact_vector3&v){return v.x.is_zero()&&v.y.is_zero()&&v.z.is_zero();}exact_scalar parameter(const exact_point2&p,const exact_segment2&s){performance_count(performance_counter::geometric_exact_divisions);auto d=s.destination-s.origin;return !d.x.is_zero()?(p.x-s.origin.x)/d.x:(p.y-s.origin.y)/d.y;}exact_scalar parameter(const exact_point3&p,const exact_segment3&s){performance_count(performance_counter::geometric_exact_divisions);auto d=s.destination-s.origin;return !d.x.is_zero()?(p.x-s.origin.x)/d.x:!d.y.is_zero()?(p.y-s.origin.y)/d.y:(p.z-s.origin.z)/d.z;}int cmp0(const exact_scalar&x){return x.compare(exact_scalar(0));}bool in01(const exact_scalar&t){return cmp0(t)>=0&&t.compare(exact_scalar(1))<=0;}}
exact_vector2 operator-(const exact_point2&a,const exact_point2&b){return{a.x-b.x,a.y-b.y};}exact_vector3 operator-(const exact_point3&a,const exact_point3&b){return{a.x-b.x,a.y-b.y,a.z-b.z};}exact_point2 operator+(const exact_point2&p,const exact_vector2&v){return{p.x+v.x,p.y+v.y};}exact_point3 operator+(const exact_point3&p,const exact_vector3&v){return{p.x+v.x,p.y+v.y,p.z+v.z};}exact_vector2 operator*(const exact_vector2&v,const exact_scalar&s){return{v.x*s,v.y*s};}exact_vector3 operator*(const exact_vector3&v,const exact_scalar&s){return{v.x*s,v.y*s,v.z*s};}
exact_scalar dot(const exact_vector2&a,const exact_vector2&b){return a.x*b.x+a.y*b.y;}exact_scalar dot(const exact_vector3&a,const exact_vector3&b){return a.x*b.x+a.y*b.y+a.z*b.z;}exact_vector3 cross(const exact_vector3&a,const exact_vector3&b){return{a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
exact_sign dot_sign_exact(const exact_vector2&a,const exact_vector2&b){return dot(a,b).sign();}exact_sign dot_sign_exact(const exact_vector3&a,const exact_vector3&b){return dot(a,b).sign();}
namespace{
std::atomic<predicate_execution_policy>test_execution_policy{predicate_execution_policy::automatic};
template<class Filter,class Exact>exact_sign filtered(predicate_execution_policy policy,performance_counter accepted,performance_counter fallback,Filter filter,Exact exact){
 if(policy==predicate_execution_policy::automatic)policy=test_execution_policy.load(std::memory_order_relaxed);
 if(policy!=predicate_execution_policy::exact_only&&policy!=predicate_execution_policy::force_exact_fallback){if(auto sign=filter()){performance_count(performance_counter::filter_accepts);performance_count(accepted);return *sign;}performance_count(performance_counter::filter_fallbacks);performance_count(fallback);}else if(policy==predicate_execution_policy::force_exact_fallback){performance_count(performance_counter::filter_fallbacks);performance_count(fallback);}performance_count(performance_counter::exact_fallbacks);return exact();
}}
predicate_execution_policy exact_filter_policy::exchange_test_execution_policy(predicate_execution_policy policy)noexcept{return test_execution_policy.exchange(policy,std::memory_order_relaxed);}
exact_sign dot_sign(const exact_vector2&a,const exact_vector2&b,predicate_execution_policy p,coordinate_tag t){performance_count(performance_counter::dot_sign_calls);return filtered(p,performance_counter::dot_sign_filter_accepts,performance_counter::dot_sign_filter_fallbacks,[&]{return exact_filter_policy::dot_sign(a,b,t);},[&]{return dot_sign_exact(a,b);});}
exact_sign dot_sign(const exact_vector3&a,const exact_vector3&b,predicate_execution_policy p,coordinate_tag t){performance_count(performance_counter::dot_sign_calls);return filtered(p,performance_counter::dot_sign_filter_accepts,performance_counter::dot_sign_filter_fallbacks,[&]{return exact_filter_policy::dot_sign(a,b,t);},[&]{return dot_sign_exact(a,b);});}
exact_sign orient2d_exact(const exact_point2&a,const exact_point2&b,const exact_point2&c){auto u=b-a,v=c-a;return sg(u.x*v.y-u.y*v.x);}exact_sign orient3d_exact(const exact_point3&a,const exact_point3&b,const exact_point3&c,const exact_point3&d){return sg(dot(b-a,cross(c-a,d-a)));}
exact_sign orient2d(const exact_point2&a,const exact_point2&b,const exact_point2&c,predicate_execution_policy p,coordinate_tag t){performance_count(performance_counter::orient2d_calls);return filtered(p,performance_counter::orient2d_filter_accepts,performance_counter::orient2d_filter_fallbacks,[&]{return exact_filter_policy::orient2d(a,b,c,t);},[&]{return orient2d_exact(a,b,c);});}
exact_sign orient3d(const exact_point3&a,const exact_point3&b,const exact_point3&c,const exact_point3&d,predicate_execution_policy p,coordinate_tag t){performance_count(performance_counter::orient3d_calls);return filtered(p,performance_counter::orient3d_filter_accepts,performance_counter::orient3d_filter_fallbacks,[&]{return exact_filter_policy::orient3d(a,b,c,d,t);},[&]{return orient3d_exact(a,b,c,d);});}
int lexicographic_compare(const exact_point2&a,const exact_point2&b){int c=a.x.compare(b.x);return c?c:a.y.compare(b.y);}int lexicographic_compare(const exact_point3&a,const exact_point3&b){int c=a.x.compare(b.x);if(c)return c;c=a.y.compare(b.y);return c?c:a.z.compare(b.z);}exact_point2 project(const exact_point3&p,projection_axis a){return a==projection_axis::drop_x?exact_point2{p.y,p.z}:a==projection_axis::drop_y?exact_point2{p.z,p.x}:exact_point2{p.x,p.y};}
status_or<exact_plane3>support_plane(const exact_point3&a,const exact_point3&b,const exact_point3&c){performance_count(performance_counter::support_plane_constructions);auto n=cross(b-a,c-a);if(z(n))return make_error(boolean_error_code::input_contract_error,boolean_stage::input_validation,"collinear_plane_points");auto A=n.x,B=n.y,C=n.z,D=(A*a.x+B*a.y+C*a.z).negated();big_uint den=A.denominator()*B.denominator()*C.denominator()*D.denominator();big_int ai=A.numerator()*big_int(integer_sign::positive,divide(den,A.denominator()).first),bi=B.numerator()*big_int(integer_sign::positive,divide(den,B.denominator()).first),ci=C.numerator()*big_int(integer_sign::positive,divide(den,C.denominator()).first),di=D.numerator()*big_int(integer_sign::positive,divide(den,D.denominator()).first);auto g=gcd(gcd(ai.magnitude(),bi.magnitude()),gcd(ci.magnitude(),di.magnitude()));ai=divide(ai,big_int(integer_sign::positive,g)).first;bi=divide(bi,big_int(integer_sign::positive,g)).first;ci=divide(ci,big_int(integer_sign::positive,g)).first;di=divide(di,big_int(integer_sign::positive,g)).first;big_int*first=!ai.is_zero()?&ai:!bi.is_zero()?&bi:!ci.is_zero()?&ci:&di;orientation_parity parity=first->sign()==integer_sign::negative?orientation_parity::opposite:orientation_parity::agree;if(parity==orientation_parity::opposite){ai=ai.negated();bi=bi.negated();ci=ci.negated();di=di.negated();}return exact_plane3{ai,bi,ci,di,parity};}
exact_sign plane_side_exact(const exact_plane3&p,const exact_point3&q){return eval(p,q).sign();}exact_sign plane_side(const exact_plane3&p,const exact_point3&q,predicate_execution_policy x,coordinate_tag t){performance_count(performance_counter::plane_side_calls);return filtered(x,performance_counter::plane_side_filter_accepts,performance_counter::plane_side_filter_fallbacks,[&]{return exact_filter_policy::plane_side(p,q,t);},[&]{return plane_side_exact(p,q);});}projection_axis dominant_projection(const exact_plane3&p){auto a=p.a.magnitude(),b=p.b.magnitude(),c=p.c.magnitude();return a.compare(b)>=0&&a.compare(c)>=0?projection_axis::drop_x:b.compare(c)>=0?projection_axis::drop_y:projection_axis::drop_z;}
point_line_relation classify_point_line(const exact_point2&p,const exact_line2&l){if(z(l.direction))throw std::invalid_argument("zero line direction");return sg(l.direction.x*(p.y-l.anchor.y)-l.direction.y*(p.x-l.anchor.x))==exact_sign::zero?point_line_relation::on_carrier:point_line_relation::off_carrier;}point_line_relation classify_point_line(const exact_point3&p,const exact_line3&l){if(z(l.direction))throw std::invalid_argument("zero line direction");return z(cross(p-l.anchor,l.direction))?point_line_relation::on_carrier:point_line_relation::off_carrier;}
point_segment_relation classify_point_segment(const exact_point2&p,const exact_segment2&s){auto d=s.destination-s.origin;if(z(d))return p==s.origin?point_segment_relation::at_origin:point_segment_relation::off_carrier;if(classify_point_line(p,{s.origin,d})==point_line_relation::off_carrier)return point_segment_relation::off_carrier;auto t=parameter(p,s);int a=cmp0(t),b=t.compare(exact_scalar(1));return a<0?point_segment_relation::before_origin:a==0?point_segment_relation::at_origin:b<0?point_segment_relation::open_interior:b==0?point_segment_relation::at_destination:point_segment_relation::after_destination;}point_segment_relation classify_point_segment(const exact_point3&p,const exact_segment3&s){auto d=s.destination-s.origin;if(z(d))return p==s.origin?point_segment_relation::at_origin:point_segment_relation::off_carrier;if(classify_point_line(p,{s.origin,d})==point_line_relation::off_carrier)return point_segment_relation::off_carrier;auto t=parameter(p,s);int a=cmp0(t),b=t.compare(exact_scalar(1));return a<0?point_segment_relation::before_origin:a==0?point_segment_relation::at_origin:b<0?point_segment_relation::open_interior:b==0?point_segment_relation::at_destination:point_segment_relation::after_destination;}
status_or<point_region_relation>classify_point_polygon(const exact_point2&p,const std::vector<exact_point2>&v){if(v.size()<3)return make_error(boolean_error_code::input_contract_error,boolean_stage::input_validation,"polygon_size");bool inside=false;for(std::size_t i=0,j=v.size()-1;i<v.size();j=i++){performance_count(performance_counter::point_in_polygon_edge_tests);if(v[i]==v[j])return make_error(boolean_error_code::input_contract_error,boolean_stage::input_validation,"zero_polygon_edge");auto r=classify_point_segment(p,{v[j],v[i]});if(r==point_segment_relation::at_origin)return point_region_relation{point_region_kind::boundary_vertex,j};if(r==point_segment_relation::at_destination)return point_region_relation{point_region_kind::boundary_vertex,i};if(r==point_segment_relation::open_interior)return point_region_relation{point_region_kind::boundary_edge_interior,j};bool up=v[j].y.compare(p.y)<=0&&v[i].y.compare(p.y)>0,down=v[i].y.compare(p.y)<=0&&v[j].y.compare(p.y)>0;if((up&&orient2d(v[j],v[i],p)==exact_sign::positive)||(down&&orient2d(v[j],v[i],p)==exact_sign::negative))inside=!inside;}return point_region_relation{inside?point_region_kind::open_interior:point_region_kind::outside,0};}
status_or<point_region_relation>classify_point_triangle(const exact_point3&p,const exact_point3&a,const exact_point3&b,const exact_point3&c){auto pl=support_plane(a,b,c);if(!pl.has_value())return pl.error();if(plane_side(pl.value(),p)!=exact_sign::zero)return point_region_relation{};auto ax=dominant_projection(pl.value());std::vector<exact_point2>tri{project(a,ax),project(b,ax),project(c,ax)};return classify_point_polygon(project(p,ax),tri);}
polygon_intersection_kind relate_triangles(const exact_triangle3&x,const exact_triangle3&y){auto px=support_plane(x.a,x.b,x.c),py=support_plane(y.a,y.b,y.c);if(!px.has_value()||!py.has_value())throw std::invalid_argument("degenerate triangle");std::array<exact_segment3,3>xe{{{x.a,x.b},{x.b,x.c},{x.c,x.a}}},ye{{{y.a,y.b},{y.b,y.c},{y.c,y.a}}};polygon_intersection_kind boundary=polygon_intersection_kind::disjoint;for(const auto&a:xe)for(const auto&b:ye){auto r=relate_segments(a,b);if(r.dimension==intersection_dimension::segment)return polygon_intersection_kind::segment;if(r.dimension==intersection_dimension::point)boundary=polygon_intersection_kind::point;}auto pp=intersect_planes(px.value(),py.value());if(pp.kind==plane_plane_kind::parallel_disjoint)return polygon_intersection_kind::disjoint;if(pp.kind==plane_plane_kind::coincident_same||pp.kind==plane_plane_kind::coincident_opposite){auto ax=dominant_projection(px.value());std::array<exact_point2,3>a{{project(x.a,ax),project(x.b,ax),project(x.c,ax)}},b{{project(y.a,ax),project(y.b,ax),project(y.c,ax)}};polygon_intersection_kind out=boundary;for(std::size_t i=0;i<3;++i)for(std::size_t j=0;j<3;++j){auto r=relate_segments({a[i],a[(i+1)%3]},{b[j],b[(j+1)%3]});if(r.dimension==intersection_dimension::segment)out=polygon_intersection_kind::segment;else if(r.dimension==intersection_dimension::point){if(r.point_kind==segment_point_kind::proper_crossing)return polygon_intersection_kind::area;if(out==polygon_intersection_kind::disjoint)out=polygon_intersection_kind::point;}}std::vector<exact_point2>av(a.begin(),a.end()),bv(b.begin(),b.end());for(const auto&q:a){auto r=classify_point_polygon(q,bv);if(r.has_value()&&r.value().kind==point_region_kind::open_interior)return polygon_intersection_kind::area;}for(const auto&q:b){auto r=classify_point_polygon(q,av);if(r.has_value()&&r.value().kind==point_region_kind::open_interior)return polygon_intersection_kind::area;}return out;}polygon_intersection_kind out=boundary;auto check=[&](const auto&edges,const exact_plane3&plane,const exact_triangle3&tri){for(const auto&e:edges){auto r=relate_segment_plane(e,plane);if(!r.point)continue;auto q=classify_point_triangle(*r.point,tri.a,tri.b,tri.c);if(!q.has_value()||q.value().kind==point_region_kind::outside)continue;if(q.value().kind==point_region_kind::open_interior&&r.kind==segment_plane_kind::proper_crossing)return polygon_intersection_kind::segment;out=polygon_intersection_kind::point;}return out;};if(check(xe,py.value(),y)==polygon_intersection_kind::segment)return polygon_intersection_kind::segment;if(check(ye,px.value(),x)==polygon_intersection_kind::segment)return polygon_intersection_kind::segment;return out;}
polygon_intersection_kind relate_polygons(const std::vector<exact_triangle3>&a,const std::vector<exact_triangle3>&b){polygon_intersection_kind out=polygon_intersection_kind::disjoint;for(const auto&x:a)for(const auto&y:b){auto r=relate_triangles(x,y);if(static_cast<unsigned>(r)>static_cast<unsigned>(out))out=r;if(out==polygon_intersection_kind::area)return out;}return out;}
status_or<solid_point_kind>classify_point_closed_triangle_shell(const exact_point3&p,const std::vector<exact_triangle3>&tris){for(const auto&t:tris){auto r=classify_point_triangle(p,t.a,t.b,t.c);if(r.has_value()&&r.value().kind!=point_region_kind::outside)return solid_point_kind::boundary;}const std::array<exact_vector3,5>dirs{{{exact_scalar(1),exact_scalar(2),exact_scalar(4)},{exact_scalar(2),exact_scalar(5),exact_scalar(11)},{exact_scalar(3),exact_scalar(7),exact_scalar(17)},{exact_scalar(5),exact_scalar(13),exact_scalar(29)},{exact_scalar(7),exact_scalar(19),exact_scalar(43)}}};for(const auto&d:dirs){std::size_t crossings=0;bool degenerate=false;for(const auto&t:tris){auto pl=support_plane(t.a,t.b,t.c);if(!pl.has_value())return pl.error();auto hit=intersect_line_plane({p,d},pl.value());if(hit.kind!=line_plane_kind::unique||!hit.parameter||hit.parameter->sign()!=exact_sign::positive)continue;auto r=classify_point_triangle(*hit.point,t.a,t.b,t.c);if(!r.has_value())return r.error();if(r.value().kind==point_region_kind::open_interior)++crossings;else if(r.value().kind!=point_region_kind::outside){degenerate=true;break;}}if(!degenerate)return crossings%2?solid_point_kind::inside:solid_point_kind::outside;}return make_error(boolean_error_code::internal_invariant_error,boolean_stage::input_validation,"shell_point_location_degenerate_rays");}

struct ray_source_attribution {
 std::optional<facet_id> facet;
 std::uint32_t primitive=0;
 std::optional<std::array<original_vertex_id,3>> vertices;
 const std::vector<exact_point3>* ring=nullptr;
 const std::vector<original_vertex_id>* ring_vertices=nullptr;
 const std::vector<std::vector<facet_id>>* vertex_fans=nullptr;
};
template<class Triangle, class Geometry, class Source>
status_or<formal_operand_location> locate_formal_open_point_impl(const formal_open_point_view&q,const std::vector<Triangle>&tris,std::uint8_t first_direction,Geometry geometry,Source source){
 performance_count(performance_counter::shell_location_queries);
 performance_count(performance_counter::classification_source_triangles,tris.size());
 std::vector<exact_vector3>dirs{
  {exact_scalar(1),exact_scalar(0),exact_scalar(0)},{exact_scalar(0),exact_scalar(1),exact_scalar(0)},
  {exact_scalar(0),exact_scalar(0),exact_scalar(1)},{exact_scalar(1),exact_scalar(1),exact_scalar(1)},
  {exact_scalar(1),exact_scalar(2),exact_scalar(4)},{exact_scalar(1),exact_scalar(4),exact_scalar(2)},
  {exact_scalar(2),exact_scalar(1),exact_scalar(4)},{exact_scalar(4),exact_scalar(1),exact_scalar(2)},
  {exact_scalar(2),exact_scalar(4),exact_scalar(1)},{exact_scalar(4),exact_scalar(2),exact_scalar(1)}};
 // A finite set of facet planes excludes only finitely many directions.
 // Select the first stable-key-derived moment-curve direction outside all of
 // them. This is the exact generic-ray fallback; no epsilon is instantiated.
 const auto seed=static_cast<std::uint64_t>(q.key.local_rank)+q.key.stable_features.size()+1;
 for(std::uint64_t step=0;dirs.size()<12;++step){
  const auto k=seed+step;exact_vector3 candidate{exact_scalar(1),exact_scalar(static_cast<std::int64_t>(k)),exact_scalar(static_cast<std::int64_t>(k*k))};bool generic=true;
   for(const auto&item:tris){const auto&t=geometry(item);auto pl=support_plane(t.a,t.b,t.c);if(!pl.has_value())return pl.error();exact_vector3 n{ri(pl.value().a),ri(pl.value().b),ri(pl.value().c)};if(dot_sign(n,candidate)==exact_sign::zero){generic=false;break;}}
   if(generic)dirs.push_back(std::move(candidate));
 }
 // Compare a+b*epsilon with zero for sufficiently small positive epsilon.
 auto formal_sign=[](const exact_scalar&a,const exact_scalar&b){auto s=a.sign();return s==exact_sign::zero?b.sign():s;};
 if(first_direction>=dirs.size())return make_error(boolean_error_code::internal_invariant_error,boolean_stage::cell_classification,"formal_ray_direction_range");
 const auto start=static_cast<std::size_t>(first_direction)%dirs.size();
 const auto attempts=first_direction==0?dirs.size():dirs.size()-1;
 for(std::size_t offset=0;offset<attempts;++offset){const auto di=(start+offset)%dirs.size();
  formal_operand_location out;out.ray_direction_index=static_cast<std::uint8_t>(di);out.ray_direction=dirs[di];bool ambiguous=false;std::int64_t degree=0;
   for(std::size_t ti=0;ti<tris.size();++ti){performance_count(performance_counter::exact_ray_facet_tests);const auto&t=geometry(tris[ti]);auto pl=support_plane(t.a,t.b,t.c);if(!pl.has_value())return pl.error();
   exact_vector3 n{ri(pl.value().a),ri(pl.value().b),ri(pl.value().c)};if(pl.value().oriented==orientation_parity::opposite)n=n*exact_scalar(-1);
    auto den=dot(n,dirs[di]);if(den.is_zero()){auto c0=eval(pl.value(),q.base);if(c0.sign()==exact_sign::zero&&dot_sign(n,q.infinitesimal_direction)==exact_sign::zero){ambiguous=true;break;}continue;}
    performance_count(performance_counter::geometric_exact_divisions,2);auto tc=eval(pl.value(),q.base).negated()/den,te=dot(n,q.infinitesimal_direction).negated()/den;
   if(formal_sign(tc,te)!=exact_sign::positive)continue;
   auto x0=q.base+dirs[di]*tc;auto de=dirs[di]*te;exact_vector3 x1{q.infinitesimal_direction.x+de.x,q.infinitesimal_direction.y+de.y,q.infinitesimal_direction.z+de.z};
   auto ax=dominant_projection(pl.value());auto a=project(t.a,ax),b=project(t.b,ax),c=project(t.c,ax),x=project(x0,ax);
   exact_vector2 xe=ax==projection_axis::drop_x?exact_vector2{x1.y,x1.z}:ax==projection_axis::drop_y?exact_vector2{x1.z,x1.x}:exact_vector2{x1.x,x1.y};
   auto edge_sign=[&](const exact_point2&u,const exact_point2&v){auto e=v-u,w=x-u;return formal_sign(e.x*w.y-e.y*w.x,e.x*xe.y-e.y*xe.x);};
    auto orientation=orient2d(a,b,c);auto u0=orient2d(a,b,x),u1=orient2d(b,c,x),u2=orient2d(c,a,x);auto s0=edge_sign(a,b),s1=edge_sign(b,c),s2=edge_sign(c,a);if(s0==exact_sign::zero||s1==exact_sign::zero||s2==exact_sign::zero){ambiguous=true;break;}
    if(s0!=orientation||s1!=orientation||s2!=orientation)continue;
       const auto contribution=den.sign()==exact_sign::positive?1:-1;auto attribution=source(tris[ti]);const auto zeros=unsigned(u0==exact_sign::zero)+unsigned(u1==exact_sign::zero)+unsigned(u2==exact_sign::zero);auto ownership=zeros>1?formal_ray_ownership_kind::source_vertex:zeros==1?formal_ray_ownership_kind::source_edge:formal_ray_ownership_kind::facet_interior;formal_ray_hit h;h.triangle=ti;h.source_facet=attribution.facet;h.source_primitive=attribution.primitive;h.parameter_constant=tc;h.parameter_epsilon=te;h.signed_contribution=static_cast<std::int8_t>(contribution);
         if(attribution.facet){if(!attribution.ring||!attribution.ring_vertices||attribution.ring->size()<3||attribution.ring->size()!=attribution.ring_vertices->size()||(attribution.vertex_fans&&!attribution.vertex_fans->empty()&&attribution.vertex_fans->size()!=attribution.ring->size()))return make_error(boolean_error_code::internal_invariant_error,boolean_stage::cell_classification,"source_facet_ring");ownership=formal_ray_ownership_kind::facet_interior;for(std::size_t vi=0;vi<attribution.ring->size();++vi)if(x0==(*attribution.ring)[vi]){ownership=formal_ray_ownership_kind::source_vertex;h.source_vertex=(*attribution.ring_vertices)[vi];if(attribution.vertex_fans&&!attribution.vertex_fans->empty())h.source_vertex_fan=(*attribution.vertex_fans)[vi];break;}if(ownership==formal_ray_ownership_kind::facet_interior)for(std::size_t ei=0;ei<attribution.ring->size();++ei){const auto ni=(ei+1)%attribution.ring->size();if(classify_point_segment(x0,{(*attribution.ring)[ei],(*attribution.ring)[ni]})==point_segment_relation::open_interior){ownership=formal_ray_ownership_kind::source_edge;h.source_edge_direction=std::array<original_vertex_id,2>{(*attribution.ring_vertices)[ei],(*attribution.ring_vertices)[ni]};auto edge=*h.source_edge_direction;if(edge[1]<edge[0])std::swap(edge[0],edge[1]);h.source_edge=edge;break;}}}
       else if(attribution.vertices&&zeros>1){const auto vi=(u0==exact_sign::zero&&u2==exact_sign::zero)?0u:(u0==exact_sign::zero&&u1==exact_sign::zero)?1u:2u;h.source_vertex=(*attribution.vertices)[vi];}
        else if(attribution.vertices&&zeros==1){h.source_edge_direction=u0==exact_sign::zero?std::array<original_vertex_id,2>{(*attribution.vertices)[0],(*attribution.vertices)[1]}:u1==exact_sign::zero?std::array<original_vertex_id,2>{(*attribution.vertices)[1],(*attribution.vertices)[2]}:std::array<original_vertex_id,2>{(*attribution.vertices)[2],(*attribution.vertices)[0]};auto edge=*h.source_edge_direction;if(edge[1]<edge[0])std::swap(edge[0],edge[1]);h.source_edge=edge;}
       h.ownership=ownership;
       performance_count(performance_counter::accepted_ray_hits);out.hits.push_back(std::move(h));
   }
   if(ambiguous)continue;
   std::sort(out.hits.begin(),out.hits.end(),[](const formal_ray_hit&a,const formal_ray_hit&b){int c=a.parameter_constant.compare(b.parameter_constant);if(c)return c<0;c=a.parameter_epsilon.compare(b.parameter_epsilon);if(c)return c<0;if(a.source_facet!=b.source_facet)return a.source_facet<b.source_facet;if(a.source_primitive!=b.source_primitive)return a.source_primitive<b.source_primitive;return a.triangle<b.triangle;});
    std::vector<formal_ray_hit> owned;std::uint32_t group=0;
     for(std::size_t i=0;i<out.hits.size();){std::size_t end=i+1;while(end<out.hits.size()&&out.hits[end].parameter_constant==out.hits[i].parameter_constant&&out.hits[end].parameter_epsilon==out.hits[i].parameter_epsilon)++end;std::vector<formal_ray_hit> facet_owned;for(std::size_t j=i;j<end;){std::size_t next=j+1;while(next<end&&out.hits[next].source_facet&&out.hits[j].source_facet==out.hits[next].source_facet)++next;auto hit=out.hits[j];for(std::size_t k=j+1;k<next;++k){if(out.hits[k].signed_contribution!=hit.signed_contribution){ambiguous=true;break;}if(static_cast<unsigned>(out.hits[k].ownership)>static_cast<unsigned>(hit.ownership)){hit.ownership=out.hits[k].ownership;hit.source_vertex=out.hits[k].source_vertex;hit.source_vertex_fan=out.hits[k].source_vertex_fan;hit.source_vertex_fan_index=out.hits[k].source_vertex_fan_index;hit.source_edge=out.hits[k].source_edge;hit.source_edge_direction=out.hits[k].source_edge_direction;}}if(ambiguous)break;facet_owned.push_back(std::move(hit));j=next;}if(ambiguous)break;
       std::vector<bool> consumed(facet_owned.size(),false);std::int64_t group_degree=0;const auto group_begin=owned.size();for(std::size_t j=0;j<facet_owned.size();++j){if(consumed[j])continue;std::vector<std::size_t> members{j};consumed[j]=true;for(std::size_t k=j+1;k<facet_owned.size();++k){const bool same_vertex=facet_owned[j].source_vertex&&facet_owned[j].source_vertex==facet_owned[k].source_vertex;const bool same_edge=facet_owned[j].source_edge&&facet_owned[j].source_edge==facet_owned[k].source_edge;if(same_vertex||same_edge){members.push_back(k);consumed[k]=true;}}bool positive=false,negative=false;for(auto k:members){positive|=facet_owned[k].signed_contribution>0;negative|=facet_owned[k].signed_contribution<0;}const auto contribution=positive&&negative?0:(positive?1:-1);if(facet_owned[j].source_vertex){const auto&fan=facet_owned[j].source_vertex_fan;if(fan.empty())return make_error(boolean_error_code::internal_invariant_error,boolean_stage::cell_classification,"source_vertex_fan_missing");std::vector<bool>seen(fan.size(),false);for(auto k:members){if(facet_owned[k].source_vertex_fan!=fan||!facet_owned[k].source_facet)return make_error(boolean_error_code::internal_invariant_error,boolean_stage::cell_classification,"source_vertex_fan_mismatch");auto at=std::find(fan.begin(),fan.end(),*facet_owned[k].source_facet);if(at==fan.end())return make_error(boolean_error_code::internal_invariant_error,boolean_stage::cell_classification,"source_vertex_fan_member");const auto rank=static_cast<std::size_t>(at-fan.begin());if(seen[rank])return make_error(boolean_error_code::internal_invariant_error,boolean_stage::cell_classification,"source_vertex_fan_duplicate");seen[rank]=true;}std::sort(members.begin(),members.end(),[&](std::size_t a,std::size_t b){const auto ra=std::find(fan.begin(),fan.end(),*facet_owned[a].source_facet)-fan.begin(),rb=std::find(fan.begin(),fan.end(),*facet_owned[b].source_facet)-fan.begin();return ra<rb;});}for(std::size_t m=0;m<members.size();++m){auto hit=facet_owned[members[m]];hit.parameter_group=group;hit.signed_contribution=static_cast<std::int8_t>(m==0?contribution:0);hit.owns_boundary_crossing=m==0&&contribution!=0;if(hit.source_vertex&&!hit.source_vertex_fan.empty())hit.source_vertex_fan_index=static_cast<std::uint32_t>(std::find(hit.source_vertex_fan.begin(),hit.source_vertex_fan.end(),*hit.source_facet)-hit.source_vertex_fan.begin());if(contribution==0)hit.ownership=formal_ray_ownership_kind::tangent;owned.push_back(std::move(hit));}group_degree+=contribution;}if(group_degree==0)for(std::size_t j=group_begin;j<owned.size();++j){owned[j].ownership=formal_ray_ownership_kind::tangent;owned[j].signed_contribution=0;owned[j].owns_boundary_crossing=false;}degree+=group_degree;++group;i=end;}
   if(ambiguous)continue;out.hits=std::move(owned);if(degree<0||degree>1)return make_error(boolean_error_code::internal_invariant_error,boolean_stage::cell_classification,"formal_signed_degree_out_of_range");
  out.signed_degree=static_cast<std::int32_t>(degree);out.location=degree==1?formal_operand_location_kind::inside:formal_operand_location_kind::outside;return out;
 }
 return make_error(boolean_error_code::internal_invariant_error,boolean_stage::cell_classification,"formal_point_location_unresolved");
}
status_or<formal_operand_location> locate_formal_open_point(const formal_open_point_view&q,const std::vector<exact_triangle3>&tris,std::uint8_t first_direction){
   return locate_formal_open_point_impl(q,tris,first_direction,[](const exact_triangle3&t){return t;},[](const exact_triangle3&){return ray_source_attribution{};});
}
status_or<formal_operand_location> locate_formal_open_point(const formal_open_point_view&q,const std::vector<sourced_exact_triangle3>&tris,std::uint8_t first_direction){
   return locate_formal_open_point_impl(q,tris,first_direction,[](const sourced_exact_triangle3&t){return t.triangle;},[](const sourced_exact_triangle3&t){return ray_source_attribution{t.source_facet,t.source_primitive,t.source_vertices,&t.source_ring,&t.source_ring_vertices,&t.source_vertex_fans};});
}
bool validate_formal_ray_ownership_evidence(const formal_operand_location&location) noexcept{
 std::uint32_t previous_group=0;bool first=true;std::int64_t degree=0;
 for(const auto&h:location.hits){
  if((!first&&h.parameter_group<previous_group)||(h.owns_boundary_crossing!=(h.signed_contribution!=0)))return false;
  first=false;previous_group=h.parameter_group;degree+=h.signed_contribution;
   if(h.source_vertex){
    if(h.source_vertex_fan.empty()||!h.source_vertex_fan_index||*h.source_vertex_fan_index>=h.source_vertex_fan.size()||!h.source_facet||h.source_vertex_fan[*h.source_vertex_fan_index]!=*h.source_facet)return false;
    auto fan=h.source_vertex_fan;std::sort(fan.begin(),fan.end());if(std::adjacent_find(fan.begin(),fan.end())!=fan.end())return false;
   }else if(!h.source_vertex_fan.empty()||h.source_vertex_fan_index)return false;
   if(h.ownership==formal_ray_ownership_kind::source_edge){
   if(!h.source_edge||!h.source_edge_direction)return false;
   auto edge=*h.source_edge_direction;if(edge[1]<edge[0])std::swap(edge[0],edge[1]);if(edge!=*h.source_edge)return false;
  }else if(h.source_edge_direction)return false;
  if(h.ownership==formal_ray_ownership_kind::tangent&&(h.signed_contribution!=0||h.owns_boundary_crossing))return false;
 }
 return degree==location.signed_degree&&degree>=0&&degree<=1&&
        location.location==(degree==1?formal_operand_location_kind::inside:formal_operand_location_kind::outside);
}
line_line_result2 intersect_lines(const exact_line2&a,const exact_line2&b){if(z(a.direction)||z(b.direction))throw std::invalid_argument("zero line direction");auto det=a.direction.x*b.direction.y-a.direction.y*b.direction.x;if(det.is_zero())return{classify_point_line(b.anchor,a)==point_line_relation::on_carrier?line_line_kind::coincident:line_line_kind::parallel_disjoint,{},{},{}};auto delta=b.anchor-a.anchor;auto t=(delta.x*b.direction.y-delta.y*b.direction.x)/det;auto u=(delta.x*a.direction.y-delta.y*a.direction.x)/det;return{line_line_kind::unique,t,u,a.anchor+a.direction*t};}
segment_relation2 relate_segments(const exact_segment2&a,const exact_segment2&b){segment_relation2 r;auto da=a.destination-a.origin,db=b.destination-b.origin;if(z(da)){auto q=classify_point_segment(a.origin,b);if(q==point_segment_relation::off_carrier||q==point_segment_relation::before_origin||q==point_segment_relation::after_destination)return r;r.carrier=carrier_relation::collinear;r.dimension=intersection_dimension::point;r.point=a.origin;r.first_parameter=exact_scalar(0);r.second_parameter=z(db)?exact_scalar(0):parameter(a.origin,b);r.point_kind=(q==point_segment_relation::open_interior)?segment_point_kind::endpoint_interior:segment_point_kind::endpoint_endpoint;return r;}if(z(db)){auto x=relate_segments(b,a);r.carrier=x.carrier;r.dimension=x.dimension;r.point_kind=x.point_kind;r.point=x.point;r.first_parameter=x.second_parameter;r.second_parameter=x.first_parameter;return r;}auto ll=intersect_lines({a.origin,da},{b.origin,db});if(ll.kind==line_line_kind::parallel_disjoint)return r;if(ll.kind==line_line_kind::unique){r.carrier=carrier_relation::nonparallel_coplanar;if(in01(*ll.first_parameter)&&in01(*ll.second_parameter)){r.dimension=intersection_dimension::point;r.point=ll.point;r.first_parameter=ll.first_parameter;r.second_parameter=ll.second_parameter;bool ia=cmp0(*ll.first_parameter)>0&&ll.first_parameter->compare(exact_scalar(1))<0,ib=cmp0(*ll.second_parameter)>0&&ll.second_parameter->compare(exact_scalar(1))<0;r.point_kind=ia&&ib?segment_point_kind::proper_crossing:ia||ib?segment_point_kind::endpoint_interior:segment_point_kind::endpoint_endpoint;}return r;}r.carrier=carrier_relation::collinear;auto t0=parameter(b.origin,a),t1=parameter(b.destination,a);bool same=t0.compare(t1)<0;auto lo=t0.compare(t1)<0?t0:t1,hi=t0.compare(t1)<0?t1:t0,L=lo.compare(exact_scalar(0))<0?exact_scalar(0):lo,H=hi.compare(exact_scalar(1))>0?exact_scalar(1):hi;if(L.compare(H)>0)return r;if(L==H){r.dimension=intersection_dimension::point;r.point=affine_interpolate(a.origin,a.destination,L);r.first_parameter=L;r.second_parameter=parameter(*r.point,b);r.point_kind=segment_point_kind::endpoint_endpoint;return r;}r.dimension=intersection_dimension::segment;r.overlap_segment=exact_segment2{affine_interpolate(a.origin,a.destination,L),affine_interpolate(a.origin,a.destination,H)};bool aContains=lo.compare(exact_scalar(0))>=0&&hi.compare(exact_scalar(1))<=0,bContains=lo.compare(exact_scalar(0))<=0&&hi.compare(exact_scalar(1))>=0;if(aContains&&bContains)r.overlap=same?overlap_kind::equal_same_direction:overlap_kind::equal_opposite_direction;else if(aContains)r.overlap=overlap_kind::first_contains_second;else if(bContains)r.overlap=overlap_kind::second_contains_first;else r.overlap=overlap_kind::partial;return r;}
segment_relation3 relate_segments(const exact_segment3&a,const exact_segment3&b){segment_relation3 out;auto da=a.destination-a.origin,db=b.destination-b.origin;if(z(da)||z(db)){auto p=z(da)?a.origin:b.origin;auto s=z(da)?b:a;auto q=classify_point_segment(p,s);if(q==point_segment_relation::off_carrier||q==point_segment_relation::before_origin||q==point_segment_relation::after_destination)return out;out.carrier=carrier_relation::collinear;out.dimension=intersection_dimension::point;out.point=p;out.first_parameter=z(da)?exact_scalar(0):parameter(p,a);out.second_parameter=z(db)?exact_scalar(0):parameter(p,b);out.point_kind=q==point_segment_relation::open_interior?segment_point_kind::endpoint_interior:segment_point_kind::endpoint_endpoint;return out;}auto n=cross(da,db);if(z(n)){if(!z(cross(b.origin-a.origin,da))){out.carrier=carrier_relation::parallel_distinct;return out;}projection_axis ax=!da.y.is_zero()||!da.z.is_zero()?projection_axis::drop_x:projection_axis::drop_y;auto rr=relate_segments(exact_segment2{project(a.origin,ax),project(a.destination,ax)},exact_segment2{project(b.origin,ax),project(b.destination,ax)});out.carrier=rr.carrier;out.dimension=rr.dimension;out.point_kind=rr.point_kind;out.overlap=rr.overlap;out.first_parameter=rr.first_parameter;out.second_parameter=rr.second_parameter;if(rr.point){auto t=*rr.first_parameter;out.point=affine_interpolate(a.origin,a.destination,t);}if(rr.overlap_segment){auto l=parameter(rr.overlap_segment->origin,{project(a.origin,ax),project(a.destination,ax)}),h=parameter(rr.overlap_segment->destination,{project(a.origin,ax),project(a.destination,ax)});out.overlap_segment=exact_segment3{affine_interpolate(a.origin,a.destination,l),affine_interpolate(a.origin,a.destination,h)};}return out;}if(dot(b.origin-a.origin,n).sign()!=exact_sign::zero){out.carrier=carrier_relation::skew;return out;}out.carrier=carrier_relation::nonparallel_coplanar;projection_axis ax=!n.x.is_zero()?projection_axis::drop_x:!n.y.is_zero()?projection_axis::drop_y:projection_axis::drop_z;auto rr=relate_segments({project(a.origin,ax),project(a.destination,ax)},{project(b.origin,ax),project(b.destination,ax)});out.dimension=rr.dimension;out.point_kind=rr.point_kind;out.first_parameter=rr.first_parameter;out.second_parameter=rr.second_parameter;if(rr.point)out.point=affine_interpolate(a.origin,a.destination,*rr.first_parameter);return out;}
line_plane_result intersect_line_plane(const exact_line3&l,const exact_plane3&p){if(z(l.direction))throw std::invalid_argument("zero line direction");auto at=eval(p,l.anchor),den=ri(p.a)*l.direction.x+ri(p.b)*l.direction.y+ri(p.c)*l.direction.z;if(p.oriented==orientation_parity::opposite)den=den.negated();if(den.is_zero())return{at.is_zero()?line_plane_kind::contained:line_plane_kind::parallel_disjoint,{},{}};auto t=at.negated()/den;return{line_plane_kind::unique,t,l.anchor+l.direction*t};}
segment_plane_relation relate_segment_plane(const exact_segment3&s,const exact_plane3&p){auto a=plane_side(p,s.origin),b=plane_side(p,s.destination);if(a==exact_sign::zero&&b==exact_sign::zero)return{segment_plane_kind::contained,{},{}};if(a==exact_sign::zero)return{segment_plane_kind::origin_on_plane,exact_scalar(0),s.origin};if(b==exact_sign::zero)return{segment_plane_kind::destination_on_plane,exact_scalar(1),s.destination};if(a==b)return{a==exact_sign::positive?segment_plane_kind::strictly_positive:segment_plane_kind::strictly_negative,{},{}};auto q=intersect_line_plane({s.origin,s.destination-s.origin},p);return{segment_plane_kind::proper_crossing,q.parameter,q.point};}
plane_plane_result intersect_planes(const exact_plane3&p,const exact_plane3&q){exact_vector3 n{ri(p.a),ri(p.b),ri(p.c)},m{ri(q.a),ri(q.b),ri(q.c)},dir=cross(n,m);if(z(dir)){exact_point3 probe{};if(!p.a.is_zero())probe.x=ri(p.d).negated()/ri(p.a);else if(!p.b.is_zero())probe.y=ri(p.d).negated()/ri(p.b);else probe.z=ri(p.d).negated()/ri(p.c);if(plane_side(q,probe)!=exact_sign::zero)return{plane_plane_kind::parallel_disjoint,{}};return{p.oriented==q.oriented?plane_plane_kind::coincident_same:plane_plane_kind::coincident_opposite,{}};}projection_axis ax=!dir.x.is_zero()?projection_axis::drop_x:!dir.y.is_zero()?projection_axis::drop_y:projection_axis::drop_z;exact_point3 x{};exact_scalar P=ri(p.d).negated(),Q=ri(q.d).negated(),det;if(ax==projection_axis::drop_x){det=n.y*m.z-n.z*m.y;x.y=(P*m.z-n.z*Q)/det;x.z=(n.y*Q-P*m.y)/det;}else if(ax==projection_axis::drop_y){det=n.z*m.x-n.x*m.z;x.z=(P*m.x-n.x*Q)/det;x.x=(n.z*Q-P*m.z)/det;}else{det=n.x*m.y-n.y*m.x;x.x=(P*m.y-n.y*Q)/det;x.y=(n.x*Q-P*m.x)/det;}return{plane_plane_kind::nonparallel,exact_line3{x,dir}};}
exact_point2 affine_interpolate(const exact_point2&a,const exact_point2&b,const exact_scalar&t){return a+(b-a)*t;}exact_point3 affine_interpolate(const exact_point3&a,const exact_point3&b,const exact_scalar&t){return a+(b-a)*t;}
symbolic_result<exact_sign,open_side_decision>open_side(const exact_plane3&p,const exact_point3&q,bool positive,const perturbation_key&k){auto u=plane_side(p,q);return{u,u==exact_sign::zero?std::optional<open_side_decision>(positive?open_side_decision::positive:open_side_decision::negative):std::nullopt,k};}

status_or<exact_carrier_radial_order> rank_planes_around_carrier(const exact_vector3&d,const std::vector<exact_plane3>&planes){
 if(z(d))return make_error(boolean_error_code::internal_invariant_error,boolean_stage::global_arrangement,"zero_carrier");
 exact_vector3 axis=!d.x.is_zero()?exact_vector3{d.y.negated(),d.x,exact_scalar(0)}:exact_vector3{exact_scalar(0),d.z.negated(),d.y};
 exact_vector3 second=cross(d,axis);struct item{std::size_t index;exact_vector3 ray;exact_scalar x,y;};std::vector<item>items;
 for(std::size_t i=0;i<planes.size();++i){exact_vector3 n{exact_scalar(planes[i].a,big_uint(1)),exact_scalar(planes[i].b,big_uint(1)),exact_scalar(planes[i].c,big_uint(1))};if(planes[i].oriented==orientation_parity::opposite)n=n*exact_scalar(-1);auto ray=cross(n,d);if(z(ray))return make_error(boolean_error_code::internal_invariant_error,boolean_stage::global_arrangement,"carrier_plane_parallel");items.push_back({i,ray,dot(ray,axis),dot(ray,second)});}
 auto upper=[](const item&i){return exact_scalar(0)<i.y||(i.y.is_zero()&&!(i.x<exact_scalar(0)));};
 std::sort(items.begin(),items.end(),[&](const item&a,const item&b){bool au=upper(a),bu=upper(b);if(au!=bu)return au;auto c=a.x*b.y-a.y*b.x;if(!c.is_zero())return exact_scalar(0)<c;return a.index<b.index;});exact_carrier_radial_order out;out.carrier=d;
 for(const auto&i:items){if(out.layers.empty()||!z(cross(out.layers.back().ray,i.ray))||dot(out.layers.back().ray,i.ray)<exact_scalar(0))out.layers.push_back({{},i.ray});out.layers.back().members.push_back(i.index);}return out;
}
status_or<exact_cone_witness>construct_strict_cone_witness(const std::vector<strict_cone_constraint>&constraints){
 if(constraints.empty())return exact_cone_witness{exact_vector3{exact_scalar(1),exact_scalar(0),exact_scalar(0)}, {}};exact_vector3 d{};for(const auto&c:constraints){auto q=c.normal*(c.required==exact_sign::negative?exact_scalar(-1):exact_scalar(1));d.x=d.x+q.x;d.y=d.y+q.y;d.z=d.z+q.z;}
 auto evaluate=[&](const exact_vector3&v){std::vector<exact_sign>r;for(const auto&c:constraints){auto q=dot(c.normal,v);auto s=q<exact_scalar(0)?exact_sign::negative:q.is_zero()?exact_sign::zero:exact_sign::positive;r.push_back(s);}return r;};auto signs=evaluate(d);bool ok=true;for(std::size_t i=0;i<signs.size();++i)ok&=signs[i]==constraints[i].required;if(!ok){for(std::size_t i=0;i<constraints.size()&&!ok;++i){d=constraints[i].normal*(constraints[i].required==exact_sign::negative?exact_scalar(-1):exact_scalar(1));signs=evaluate(d);ok=true;for(std::size_t j=0;j<signs.size();++j)ok&=signs[j]==constraints[j].required;}}if(!ok)return make_error(boolean_error_code::internal_invariant_error,boolean_stage::global_arrangement,"empty_strict_cone");return exact_cone_witness{d,std::move(signs)};
}
template<class T>std::vector<std::uint8_t>exact_kernel<T>::arithmetic_policy_bytes()const{canonical_encoder e;const char tag[]="YGBKER03";e.raw(reinterpret_cast<const std::uint8_t*>(tag),8);e.u16(1);e.byte(static_cast<std::uint8_t>(coordinate_type()));e.byte(32);e.u16(1);e.u16(1);e.u16(1);e.u16(1);e.u16(1);e.u16(exact_filter_policy::orient2d_proof_version);e.u16(exact_filter_policy::orient3d_proof_version);e.u16(exact_filter_policy::plane_side_proof_version);e.u16(exact_filter_policy::dot_sign_proof_version);e.u16(1);e.u16(1);return e.bytes();}template class exact_kernel<float>;template class exact_kernel<double>;
} }
