//YgorMathDelaunayViaVoronoi.h

#pragma once
#ifndef YGOR_MATH_DELAUNAY_VIA_VORONOI_H_
#define YGOR_MATH_DELAUNAY_VIA_VORONOI_H_

#include <vector>

#include "YgorDefinitions.h"
#include "YgorMath.h"


// Perform 2D Delaunay triangulation of vertices on a planar surface via the dual
// Voronoi diagram generated by Fortune's sweep-line algorithm.
//
// The input vertices are vec2's representing planar x-y coordinates.
//
// Returns an fv_surface_mesh containing the triangulation as faces. The mesh is
// not watertight, and represents a 'patch' of surface. Vertices are copied to the
// mesh, so no input vertices are modified.
//
// Invalid input (for example, fewer than 3 vertices, non-finite coordinates, or
// collinear/coincident geometry) and unexpected triangulation failures are
// reported by throwing an exception with a diagnostic message.
//
// The implementation follows Fortune's sweep-line construction of the Voronoi
// diagram and extracts the dual Delaunay triangulation from the sweep events.
// Degenerate polygonal faces produced by co-circular inputs are triangulated in a
// deterministic post-pass, and a guarded fallback to the lifting-based
// triangulator is used only when the sweep encounters an unresolved degenerate
// configuration.
//
// Primary references:
//  - Fortune SJ. A sweepline algorithm for Voronoi diagrams. Algorithmica.
//    1987;2:153-174.
//  - Fortune SJ. Numerical stability of algorithms for 2D Delaunay triangulations.
//    International Journal of Computational Geometry & Applications.
//    1995;5(1-2):193-213.
//  - Shewchuk JR. Adaptive Precision Floating-Point Arithmetic and Fast Robust
//    Geometric Predicates. Discrete & Computational Geometry. 1997;18:305-363.
//
// Robust orientation and in-circle sign tests are evaluated using adaptive
// arithmetic wrappers from YgorMath.
template <class T, class I>
fv_surface_mesh<T, I>
Delaunay_Triangulation_2_via_Voronoi(const std::vector<vec2<T>> &verts);


#endif // YGOR_MATH_DELAUNAY_VIA_VORONOI_H_
